In [47]:
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split, GridSearchCV, cross_validate
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, mean_squared_error
import matplotlib.pyplot as plt
from xgboost import XGBClassifier, XGBRegressor
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from scipy import stats
pd.set_option('display.max_rows',891)

# function to compute loss function
loss = -y(i)log(f_wb(x) + (1-y(i))log(1-f_wb(x))

In [2]:
def loss_funct(w, b, x, y):
    loss = 0
    for i in range(x.shape[0]):
        z = np.dot(w, x[i]) + b
        f_wb = 1/(1+np.exp(-1*z))
        loss = loss + -1*y[i]*np.log(f_wb) + (1-y[i])*np.log(1-f_wb)
    return loss

# function to compute cost function J(w,b)

In [3]:
def cost_funct(w, b, x, y):
    m = x.shape[0] # number of train example
    cost = 0  # initalize cost by zero
    for i in range(m):
        loss = loss_funct(w, b, x, y)
        cost = cost + loss
    return cost

# function to compute gradient descent
repeat{
    wj = wj - alpha x dJ(wi,b)âˆ•dwi
    
    b = b - alpha x dJ(w,b)/db 
    }

In [4]:
def compute_gradient(w, b, x, y):
    d_dw = np.array([i*0 for i in range(x.shape[1])])
    d_dwj = []
    d_db = 0
    for i in range(x.shape[0]):
        d_dwj = []
        z = np.dot(w, x[i]) + b
        f_wb = 1/(1+np.exp(-1*z))
        for j in range(x.shape[1]):
            a = (f_wb - y[i])*x[i][j]
            d_dwj.append(a)
        d_dw = d_dw + np.array(d_dwj)
        d_db = d_db + (f_wb - y[i])
    
    d_dw = np.array(d_dw)
    print('dJ_dw : ',d_dw)
    print('\n')
        
    return d_dw/x.shape[0], d_db/x.shape[0]

In [5]:
def find_best_param(w, b, x, y, alpha):
    for k in range(700):
        d_dw, d_db = compute_gradient(w, b, x, y)
        temp_w = w - alpha*d_dw
        temp_b = b - alpha*d_db
        
        w = temp_w
        b = temp_b
        print(loss_funct(w, b, x, y))
    return w, b

In [6]:
def plot_decision_boundary(w, b, x, y):
    z = []
    g_z = []
    for i in range(x.shape[0]):
        z.append(np.dot(w, x[i]) + b)
        g_z.append(1/(1+np.exp(-1*z[i])))
    plt.plot(z, g_z, '.')
    plt.xlabel('z')

In [7]:
def dummies(df, obj):
    for i in obj:
        dum = pd.get_dummies(df[i])
        dum.columns = i+'_'+dum.columns  #rename the column by merge the name of original column and value
        for j in dum.columns:
            df[j] = dum[j]  # update the dataframe origin
        df = df.drop(i, axis=1)  # drop the column origin (column that are used to dummies)
    return df

# read data

In [8]:
df = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

features = [i for i in test.columns]
target = 'Survived'

# output informations about data

In [9]:
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [10]:
# drop columns
df.drop('Name', axis=1, inplace=True)
df.drop('Ticket', axis=1, inplace=True)
#df.drop('Embarked', axis=1, inplace=True)
df.drop('PassengerId', axis=1, inplace=True)
df.drop('Cabin', axis=1, inplace=True)

In [11]:
print(df.info())
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB
None
     Survived  Pclass     Sex    Age  SibSp  Parch      Fare Embarked
0           0       3    male  22.00      1      0    7.2500        S
1           1       1  female  38.00      1      0   71.2833        C
2           1       3  female  26.00      0      0    7.9250        S
3           1       1  female  35.00      1      0   53.1000        S
4           0       3    male  35.00      0      0    8.0500        S
5           0       3    male    NaN      0      0    8.4583        Q
6           0       1    male  54.00      0      0   51.8625        S
7           0       3    male   2.00      3      1   21.0750        S
8           1       3  female  27.00      0      2   11.1333        S
9           1       2  female  14.00      1      0   30.0708        C
10          1       3  female   4.00      1      1   16.7000        S
11          1       1  female  58.00      0      0   26.5500        S
12          0       3    male  20.00      0      0    8.0500        S
13          0       3    male  39.00      1      5   31.2750        S
14          0       3  female  14.00      0      0    7.8542        S
15          1       2  female  55.00      0      0   16.0000        S
16          0       3    male   2.00      4      1   29.1250        Q
17          1       2    male    NaN      0      0   13.0000        S
18          0       3  female  31.00      1      0   18.0000        S
19          1       3  female    NaN      0      0    7.2250        C
20          0       2    male  35.00      0      0   26.0000        S
21          1       2    male  34.00      0      0   13.0000        S
22          1       3  female  15.00      0      0    8.0292        Q
23          1       1    male  28.00      0      0   35.5000        S
24          0       3  female   8.00      3      1   21.0750        S
25          1       3  female  38.00      1      5   31.3875        S
26          0       3    male    NaN      0      0    7.2250        C
27          0       1    male  19.00      3      2  263.0000        S
28          1       3  female    NaN      0      0    7.8792        Q
29          0       3    male    NaN      0      0    7.8958        S
30          0       1    male  40.00      0      0   27.7208        C
31          1       1  female    NaN      1      0  146.5208        C
32          1       3  female    NaN      0      0    7.7500        Q
33          0       2    male  66.00      0      0   10.5000        S
34          0       1    male  28.00      1      0   82.1708        C
35          0       1    male  42.00      1      0   52.0000        S
36          1       3    male    NaN      0      0    7.2292        C
37          0       3    male  21.00      0      0    8.0500        S
38          0       3  female  18.00      2      0   18.0000        S
39          1       3  female  14.00      1      0   11.2417        C
40          0       3  female  40.00      1      0    9.4750        S
41          0       2  female  27.00      1      0   21.0000        S
42          0       3    male    NaN      0      0    7.8958        C
43          1       2  female   3.00      1      2   41.5792        C
44          1       3  female  19.00      0      0    7.8792        Q
45          0       3    male    NaN      0      0    8.0500        S
46          0       3    male    NaN      1      0   15.5000        Q
47          1       3  female    NaN      0      0    7.7500        Q
48          0       3    male    NaN      2      0   21.6792        C
49          0       3  female  18.00      1      0   17.8000        S
50          0       3    male   7.00      4      1   39.6875        S
51          0       3    male  21.00      0      0    7.8000        S
52          1       1  female  49.00      1      0   76.7292        C
53          1       2  female  29.00      1      0   26.0000        S
54          0       1    male  65.00      0      1   61.9792        C
55          1       1    male    NaN      0      0   35.5000        S
56          1       2  female  21.00      0      0   10.5000        S
57          0       3    male  28.50      0      0    7.2292        C
58          1       2  female   5.00      1      2   27.7500        S
59          0       3    male  11.00      5      2   46.9000        S
60          0       3    male  22.00      0      0    7.2292        C
61          1       1  female  38.00      0      0   80.0000      NaN
62          0       1    male  45.00      1      0   83.4750        S
63          0       3    male   4.00      3      2   27.9000        S
64          0       1    male    NaN      0      0   27.7208        C
65          1       3    male    NaN      1      1   15.2458        C
66          1       2  female  29.00      0      0   10.5000        S
67          0       3    male  19.00      0      0    8.1583        S
68          1       3  female  17.00      4      2    7.9250        S
69          0       3    male  26.00      2      0    8.6625        S
70          0       2    male  32.00      0      0   10.5000        S
71          0       3  female  16.00      5      2   46.9000        S
72          0       2    male  21.00      0      0   73.5000        S
73          0       3    male  26.00      1      0   14.4542        C
74          1       3    male  32.00      0      0   56.4958        S
75          0       3    male  25.00      0      0    7.6500        S
76          0       3    male    NaN      0      0    7.8958        S
77          0       3    male    NaN      0      0    8.0500        S
78          1       2    male   0.83      0      2   29.0000        S
79          1       3  female  30.00      0      0   12.4750        S
80          0       3    male  22.00      0      0    9.0000        S
81          1       3    male  29.00      0      0    9.5000        S
82          1       3  female    NaN      0      0    7.7875        Q
83          0       1    male  28.00      0      0   47.1000        S
84          1       2  female  17.00      0      0   10.5000        S
85          1       3  female  33.00      3      0   15.8500        S
86          0       3    male  16.00      1      3   34.3750        S
87          0       3    male    NaN      0      0    8.0500        S
88          1       1  female  23.00      3      2  263.0000        S
89          0       3    male  24.00      0      0    8.0500        S
90          0       3    male  29.00      0      0    8.0500        S
91          0       3    male  20.00      0      0    7.8542        S
92          0       1    male  46.00      1      0   61.1750        S
93          0       3    male  26.00      1      2   20.5750        S
94          0       3    male  59.00      0      0    7.2500        S
95          0       3    male    NaN      0      0    8.0500        S
96          0       1    male  71.00      0      0   34.6542        C
97          1       1    male  23.00      0      1   63.3583        C
98          1       2  female  34.00      0      1   23.0000        S
99          0       2    male  34.00      1      0   26.0000        S
100         0       3  female  28.00      0      0    7.8958        S
101         0       3    male    NaN      0      0    7.8958        S
102         0       1    male  21.00      0      1   77.2875        S
103         0       3    male  33.00      0      0    8.6542        S
104         0       3    male  37.00      2      0    7.9250        S
105         0       3    male  28.00      0      0    7.8958        S
106         1       3  female  21.00      0      0    7.6500        S
107         1       3    male    NaN      0      0    7.7750        S
108         0       3    male  38.00      0      0    7.8958        S
109         1       3  female    NaN      1      0   24.1500        Q
110         0       1    male  47.00      0      0   52.0000        S
111         0       3  female  14.50      1      0   14.4542        C
112         0       3    male  22.00      0      0    8.0500        S
113         0       3  female  20.00      1      0    9.8250        S
114         0       3  female  17.00      0      0   14.4583        C
115         0       3    male  21.00      0      0    7.9250        S
116         0       3    male  70.50      0      0    7.7500        Q
117         0       2    male  29.00      1      0   21.0000        S
118         0       1    male  24.00      0      1  247.5208        C
119         0       3  female   2.00      4      2   31.2750        S
120         0       2    male  21.00      2      0   73.5000        S
121         0       3    male    NaN      0      0    8.0500        S
122         0       2    male  32.50      1      0   30.0708        C
123         1       2  female  32.50      0      0   13.0000        S
124         0       1    male  54.00      0      1   77.2875        S
125         1       3    male  12.00      1      0   11.2417        C
126         0       3    male    NaN      0      0    7.7500        Q
127         1       3    male  24.00      0      0    7.1417        S
128         1       3  female    NaN      1      1   22.3583        C
129         0       3    male  45.00      0      0    6.9750        S
130         0       3    male  33.00      0      0    7.8958        C
131         0       3    male  20.00      0      0    7.0500        S
132         0       3  female  47.00      1      0   14.5000        S
133         1       2  female  29.00      1      0   26.0000        S
134         0       2    male  25.00      0      0   13.0000        S
135         0       2    male  23.00      0      0   15.0458        C
136         1       1  female  19.00      0      2   26.2833        S
137         0       1    male  37.00      1      0   53.1000        S
138         0       3    male  16.00      0      0    9.2167        S
139         0       1    male  24.00      0      0   79.2000        C
140         0       3  female    NaN      0      2   15.2458        C
141         1       3  female  22.00      0      0    7.7500        S
142         1       3  female  24.00      1      0   15.8500        S
143         0       3    male  19.00      0      0    6.7500        Q
144         0       2    male  18.00      0      0   11.5000        S
145         0       2    male  19.00      1      1   36.7500        S
146         1       3    male  27.00      0      0    7.7958        S
147         0       3  female   9.00      2      2   34.3750        S
148         0       2    male  36.50      0      2   26.0000        S
149         0       2    male  42.00      0      0   13.0000        S
150         0       2    male  51.00      0      0   12.5250        S
151         1       1  female  22.00      1      0   66.6000        S
152         0       3    male  55.50      0      0    8.0500        S
153         0       3    male  40.50      0      2   14.5000        S
154         0       3    male    NaN      0      0    7.3125        S
155         0       1    male  51.00      0      1   61.3792        C
156         1       3  female  16.00      0      0    7.7333        Q
157         0       3    male  30.00      0      0    8.0500        S
158         0       3    male    NaN      0      0    8.6625        S
159         0       3    male    NaN      8      2   69.5500        S
160         0       3    male  44.00      0      1   16.1000        S
161         1       2  female  40.00      0      0   15.7500        S
162         0       3    male  26.00      0      0    7.7750        S
163         0       3    male  17.00      0      0    8.6625        S
164         0       3    male   1.00      4      1   39.6875        S
165         1       3    male   9.00      0      2   20.5250        S
166         1       1  female    NaN      0      1   55.0000        S
167         0       3  female  45.00      1      4   27.9000        S
168         0       1    male    NaN      0      0   25.9250        S
169         0       3    male  28.00      0      0   56.4958        S
170         0       1    male  61.00      0      0   33.5000        S
171         0       3    male   4.00      4      1   29.1250        Q
172         1       3  female   1.00      1      1   11.1333        S
173         0       3    male  21.00      0      0    7.9250        S
174         0       1    male  56.00      0      0   30.6958        C
175         0       3    male  18.00      1      1    7.8542        S
176         0       3    male    NaN      3      1   25.4667        S
177         0       1  female  50.00      0      0   28.7125        C
178         0       2    male  30.00      0      0   13.0000        S
179         0       3    male  36.00      0      0    0.0000        S
180         0       3  female    NaN      8      2   69.5500        S
181         0       2    male    NaN      0      0   15.0500        C
182         0       3    male   9.00      4      2   31.3875        S
183         1       2    male   1.00      2      1   39.0000        S
184         1       3  female   4.00      0      2   22.0250        S
185         0       1    male    NaN      0      0   50.0000        S
186         1       3  female    NaN      1      0   15.5000        Q
187         1       1    male  45.00      0      0   26.5500        S
188         0       3    male  40.00      1      1   15.5000        Q
189         0       3    male  36.00      0      0    7.8958        S
190         1       2  female  32.00      0      0   13.0000        S
191         0       2    male  19.00      0      0   13.0000        S
192         1       3  female  19.00      1      0    7.8542        S
193         1       2    male   3.00      1      1   26.0000        S
194         1       1  female  44.00      0      0   27.7208        C
195         1       1  female  58.00      0      0  146.5208        C
196         0       3    male    NaN      0      0    7.7500        Q
197         0       3    male  42.00      0      1    8.4042        S
198         1       3  female    NaN      0      0    7.7500        Q
199         0       2  female  24.00      0      0   13.0000        S
200         0       3    male  28.00      0      0    9.5000        S
201         0       3    male    NaN      8      2   69.5500        S
202         0       3    male  34.00      0      0    6.4958        S
203         0       3    male  45.50      0      0    7.2250        C
204         1       3    male  18.00      0      0    8.0500        S
205         0       3  female   2.00      0      1   10.4625        S
206         0       3    male  32.00      1      0   15.8500        S
207         1       3    male  26.00      0      0   18.7875        C
208         1       3  female  16.00      0      0    7.7500        Q
209         1       1    male  40.00      0      0   31.0000        C
210         0       3    male  24.00      0      0    7.0500        S
211         1       2  female  35.00      0      0   21.0000        S
212         0       3    male  22.00      0      0    7.2500        S
213         0       2    male  30.00      0      0   13.0000        S
214         0       3    male    NaN      1      0    7.7500        Q
215         1       1  female  31.00      1      0  113.2750        C
216         1       3  female  27.00      0      0    7.9250        S
217         0       2    male  42.00      1      0   27.0000        S
218         1       1  female  32.00      0      0   76.2917        C
219         0       2    male  30.00      0      0   10.5000        S
220         1       3    male  16.00      0      0    8.0500        S
221         0       2    male  27.00      0      0   13.0000        S
222         0       3    male  51.00      0      0    8.0500        S
223         0       3    male    NaN      0      0    7.8958        S
224         1       1    male  38.00      1      0   90.0000        S
225         0       3    male  22.00      0      0    9.3500        S
226         1       2    male  19.00      0      0   10.5000        S
227         0       3    male  20.50      0      0    7.2500        S
228         0       2    male  18.00      0      0   13.0000        S
229         0       3  female    NaN      3      1   25.4667        S
230         1       1  female  35.00      1      0   83.4750        S
231         0       3    male  29.00      0      0    7.7750        S
232         0       2    male  59.00      0      0   13.5000        S
233         1       3  female   5.00      4      2   31.3875        S
234         0       2    male  24.00      0      0   10.5000        S
235         0       3  female    NaN      0      0    7.5500        S
236         0       2    male  44.00      1      0   26.0000        S
237         1       2  female   8.00      0      2   26.2500        S
238         0       2    male  19.00      0      0   10.5000        S
239         0       2    male  33.00      0      0   12.2750        S
240         0       3  female    NaN      1      0   14.4542        C
241         1       3  female    NaN      1      0   15.5000        Q
242         0       2    male  29.00      0      0   10.5000        S
243         0       3    male  22.00      0      0    7.1250        S
244         0       3    male  30.00      0      0    7.2250        C
245         0       1    male  44.00      2      0   90.0000        Q
246         0       3  female  25.00      0      0    7.7750        S
247         1       2  female  24.00      0      2   14.5000        S
248         1       1    male  37.00      1      1   52.5542        S
249         0       2    male  54.00      1      0   26.0000        S
250         0       3    male    NaN      0      0    7.2500        S
251         0       3  female  29.00      1      1   10.4625        S
252         0       1    male  62.00      0      0   26.5500        S
253         0       3    male  30.00      1      0   16.1000        S
254         0       3  female  41.00      0      2   20.2125        S
255         1       3  female  29.00      0      2   15.2458        C
256         1       1  female    NaN      0      0   79.2000        C
257         1       1  female  30.00      0      0   86.5000        S
258         1       1  female  35.00      0      0  512.3292        C
259         1       2  female  50.00      0      1   26.0000        S
260         0       3    male    NaN      0      0    7.7500        Q
261         1       3    male   3.00      4      2   31.3875        S
262         0       1    male  52.00      1      1   79.6500        S
263         0       1    male  40.00      0      0    0.0000        S
264         0       3  female    NaN      0      0    7.7500        Q
265         0       2    male  36.00      0      0   10.5000        S
266         0       3    male  16.00      4      1   39.6875        S
267         1       3    male  25.00      1      0    7.7750        S
268         1       1  female  58.00      0      1  153.4625        S
269         1       1  female  35.00      0      0  135.6333        S
270         0       1    male    NaN      0      0   31.0000        S
271         1       3    male  25.00      0      0    0.0000        S
272         1       2  female  41.00      0      1   19.5000        S
273         0       1    male  37.00      0      1   29.7000        C
274         1       3  female    NaN      0      0    7.7500        Q
275         1       1  female  63.00      1      0   77.9583        S

In [12]:
df['Age'] = df['Age'].fillna(round(np.mean(df['Age'])))
df = dummies(df, ['Embarked'])
df['Sex'] = df['Sex'] == 'male'

In [13]:
print(df)

     Survived  Pclass    Sex    Age  SibSp  Parch      Fare  Embarked_C  \
0           0       3   True  22.00      1      0    7.2500           0
1           1       1  False  38.00      1      0   71.2833           1
2           1       3  False  26.00      0      0    7.9250           0
3           1       1  False  35.00      1      0   53.1000           0
4           0       3   True  35.00      0      0    8.0500           0
5           0       3   True  30.00      0      0    8.4583           0
6           0       1   True  54.00      0      0   51.8625           0
7           0       3   True   2.00      3      1   21.0750           0
8           1       3  False  27.00      0      2   11.1333           0
9           1       2  False  14.00      1      0   30.0708           1
10          1       3  False   4.00      1      1   16.7000           0
11          1       1  False  58.00      0      0   26.5500           0
12          0       3   True  20.00      0      0    8.0500           0
13          0       3   True  39.00      1      5   31.2750           0
14          0       3  False  14.00      0      0    7.8542           0
15          1       2  False  55.00      0      0   16.0000           0
16          0       3   True   2.00      4      1   29.1250           0
17          1       2   True  30.00      0      0   13.0000           0
18          0       3  False  31.00      1      0   18.0000           0
19          1       3  False  30.00      0      0    7.2250           1
20          0       2   True  35.00      0      0   26.0000           0
21          1       2   True  34.00      0      0   13.0000           0
22          1       3  False  15.00      0      0    8.0292           0
23          1       1   True  28.00      0      0   35.5000           0
24          0       3  False   8.00      3      1   21.0750           0
25          1       3  False  38.00      1      5   31.3875           0
26          0       3   True  30.00      0      0    7.2250           1
27          0       1   True  19.00      3      2  263.0000           0
28          1       3  False  30.00      0      0    7.8792           0
29          0       3   True  30.00      0      0    7.8958           0
30          0       1   True  40.00      0      0   27.7208           1
31          1       1  False  30.00      1      0  146.5208           1
32          1       3  False  30.00      0      0    7.7500           0
33          0       2   True  66.00      0      0   10.5000           0
34          0       1   True  28.00      1      0   82.1708           1
35          0       1   True  42.00      1      0   52.0000           0
36          1       3   True  30.00      0      0    7.2292           1
37          0       3   True  21.00      0      0    8.0500           0
38          0       3  False  18.00      2      0   18.0000           0
39          1       3  False  14.00      1      0   11.2417           1
40          0       3  False  40.00      1      0    9.4750           0
41          0       2  False  27.00      1      0   21.0000           0
42          0       3   True  30.00      0      0    7.8958           1
43          1       2  False   3.00      1      2   41.5792           1
44          1       3  False  19.00      0      0    7.8792           0
45          0       3   True  30.00      0      0    8.0500           0
46          0       3   True  30.00      1      0   15.5000           0
47          1       3  False  30.00      0      0    7.7500           0
48          0       3   True  30.00      2      0   21.6792           1
49          0       3  False  18.00      1      0   17.8000           0
50          0       3   True   7.00      4      1   39.6875           0
51          0       3   True  21.00      0      0    7.8000           0
52          1       1  False  49.00      1      0   76.7292           1
53          1       2  False  29.00      1      0   26.0000           0
54          0       1   True  65.00      0      1   61.9792           1
55          1       1   True  30.00      0      0   35.5000           0
56          1       2  False  21.00      0      0   10.5000           0
57          0       3   True  28.50      0      0    7.2292           1
58          1       2  False   5.00      1      2   27.7500           0
59          0       3   True  11.00      5      2   46.9000           0
60          0       3   True  22.00      0      0    7.2292           1
61          1       1  False  38.00      0      0   80.0000           0
62          0       1   True  45.00      1      0   83.4750           0
63          0       3   True   4.00      3      2   27.9000           0
64          0       1   True  30.00      0      0   27.7208           1
65          1       3   True  30.00      1      1   15.2458           1
66          1       2  False  29.00      0      0   10.5000           0
67          0       3   True  19.00      0      0    8.1583           0
68          1       3  False  17.00      4      2    7.9250           0
69          0       3   True  26.00      2      0    8.6625           0
70          0       2   True  32.00      0      0   10.5000           0
71          0       3  False  16.00      5      2   46.9000           0
72          0       2   True  21.00      0      0   73.5000           0
73          0       3   True  26.00      1      0   14.4542           1
74          1       3   True  32.00      0      0   56.4958           0
75          0       3   True  25.00      0      0    7.6500           0
76          0       3   True  30.00      0      0    7.8958           0
77          0       3   True  30.00      0      0    8.0500           0
78          1       2   True   0.83      0      2   29.0000           0
79          1       3  False  30.00      0      0   12.4750           0
80          0       3   True  22.00      0      0    9.0000           0
81          1       3   True  29.00      0      0    9.5000           0
82          1       3  False  30.00      0      0    7.7875           0
83          0       1   True  28.00      0      0   47.1000           0
84          1       2  False  17.00      0      0   10.5000           0
85          1       3  False  33.00      3      0   15.8500           0
86          0       3   True  16.00      1      3   34.3750           0
87          0       3   True  30.00      0      0    8.0500           0
88          1       1  False  23.00      3      2  263.0000           0
89          0       3   True  24.00      0      0    8.0500           0
90          0       3   True  29.00      0      0    8.0500           0
91          0       3   True  20.00      0      0    7.8542           0
92          0       1   True  46.00      1      0   61.1750           0
93          0       3   True  26.00      1      2   20.5750           0
94          0       3   True  59.00      0      0    7.2500           0
95          0       3   True  30.00      0      0    8.0500           0
96          0       1   True  71.00      0      0   34.6542           1
97          1       1   True  23.00      0      1   63.3583           1
98          1       2  False  34.00      0      1   23.0000           0
99          0       2   True  34.00      1      0   26.0000           0
100         0       3  False  28.00      0      0    7.8958           0
101         0       3   True  30.00      0      0    7.8958           0
102         0       1   True  21.00      0      1   77.2875           0
103         0       3   True  33.00      0      0    8.6542           0
104         0       3   True  37.00      2      0    7.9250           0
105         0       3   True  28.00      0      0    7.8958           0
106         1       3  False  21.00      0      0    7.6500           0
107         1       3   True  30.00      0      0    7.7750           0
108         0       3   True  38.00      0      0    7.8958           0
109         1       3  False  30.00      1      0   24.1500           0
110         0       1   True  47.00      0      0   52.0000           0
111         0       3  False  14.50      1      0   14.4542           1
112         0       3   True  22.00      0      0    8.0500           0
113         0       3  False  20.00      1      0    9.8250           0
114         0       3  False  17.00      0      0   14.4583           1
115         0       3   True  21.00      0      0    7.9250           0
116         0       3   True  70.50      0      0    7.7500           0
117         0       2   True  29.00      1      0   21.0000           0
118         0       1   True  24.00      0      1  247.5208           1
119         0       3  False   2.00      4      2   31.2750           0
120         0       2   True  21.00      2      0   73.5000           0
121         0       3   True  30.00      0      0    8.0500           0
122         0       2   True  32.50      1      0   30.0708           1
123         1       2  False  32.50      0      0   13.0000           0
124         0       1   True  54.00      0      1   77.2875           0
125         1       3   True  12.00      1      0   11.2417           1
126         0       3   True  30.00      0      0    7.7500           0
127         1       3   True  24.00      0      0    7.1417           0
128         1       3  False  30.00      1      1   22.3583           1
129         0       3   True  45.00      0      0    6.9750           0
130         0       3   True  33.00      0      0    7.8958           1
131         0       3   True  20.00      0      0    7.0500           0
132         0       3  False  47.00      1      0   14.5000           0
133         1       2  False  29.00      1      0   26.0000           0
134         0       2   True  25.00      0      0   13.0000           0
135         0       2   True  23.00      0      0   15.0458           1
136         1       1  False  19.00      0      2   26.2833           0
137         0       1   True  37.00      1      0   53.1000           0
138         0       3   True  16.00      0      0    9.2167           0
139         0       1   True  24.00      0      0   79.2000           1
140         0       3  False  30.00      0      2   15.2458           1
141         1       3  False  22.00      0      0    7.7500           0
142         1       3  False  24.00      1      0   15.8500           0
143         0       3   True  19.00      0      0    6.7500           0
144         0       2   True  18.00      0      0   11.5000           0
145         0       2   True  19.00      1      1   36.7500           0
146         1       3   True  27.00      0      0    7.7958           0
147         0       3  False   9.00      2      2   34.3750           0
148         0       2   True  36.50      0      2   26.0000           0
149         0       2   True  42.00      0      0   13.0000           0
150         0       2   True  51.00      0      0   12.5250           0
151         1       1  False  22.00      1      0   66.6000           0
152         0       3   True  55.50      0      0    8.0500           0
153         0       3   True  40.50      0      2   14.5000           0
154         0       3   True  30.00      0      0    7.3125           0
155         0       1   True  51.00      0      1   61.3792           1
156         1       3  False  16.00      0      0    7.7333           0
157         0       3   True  30.00      0      0    8.0500           0
158         0       3   True  30.00      0      0    8.6625           0
159         0       3   True  30.00      8      2   69.5500           0
160         0       3   True  44.00      0      1   16.1000           0
161         1       2  False  40.00      0      0   15.7500           0
162         0       3   True  26.00      0      0    7.7750           0
163         0       3   True  17.00      0      0    8.6625           0
164         0       3   True   1.00      4      1   39.6875           0
165         1       3   True   9.00      0      2   20.5250           0
166         1       1  False  30.00      0      1   55.0000           0
167         0       3  False  45.00      1      4   27.9000           0
168         0       1   True  30.00      0      0   25.9250           0
169         0       3   True  28.00      0      0   56.4958           0
170         0       1   True  61.00      0      0   33.5000           0
171         0       3   True   4.00      4      1   29.1250           0
172         1       3  False   1.00      1      1   11.1333           0
173         0       3   True  21.00      0      0    7.9250           0
174         0       1   True  56.00      0      0   30.6958           1
175         0       3   True  18.00      1      1    7.8542           0
176         0       3   True  30.00      3      1   25.4667           0
177         0       1  False  50.00      0      0   28.7125           1
178         0       2   True  30.00      0      0   13.0000           0
179         0       3   True  36.00      0      0    0.0000           0
180         0       3  False  30.00      8      2   69.5500           0
181         0       2   True  30.00      0      0   15.0500           1
182         0       3   True   9.00      4      2   31.3875           0
183         1       2   True   1.00      2      1   39.0000           0
184         1       3  False   4.00      0      2   22.0250           0
185         0       1   True  30.00      0      0   50.0000           0
186         1       3  False  30.00      1      0   15.5000           0
187         1       1   True  45.00      0      0   26.5500           0
188         0       3   True  40.00      1      1   15.5000           0
189         0       3   True  36.00      0      0    7.8958           0
190         1       2  False  32.00      0      0   13.0000           0
191         0       2   True  19.00      0      0   13.0000           0
192         1       3  False  19.00      1      0    7.8542           0
193         1       2   True   3.00      1      1   26.0000           0
194         1       1  False  44.00      0      0   27.7208           1
195         1       1  False  58.00      0      0  146.5208           1
196         0       3   True  30.00      0      0    7.7500           0
197         0       3   True  42.00      0      1    8.4042           0
198         1       3  False  30.00      0      0    7.7500           0
199         0       2  False  24.00      0      0   13.0000           0
200         0       3   True  28.00      0      0    9.5000           0
201         0       3   True  30.00      8      2   69.5500           0
202         0       3   True  34.00      0      0    6.4958           0
203         0       3   True  45.50      0      0    7.2250           1
204         1       3   True  18.00      0      0    8.0500           0
205         0       3  False   2.00      0      1   10.4625           0
206         0       3   True  32.00      1      0   15.8500           0
207         1       3   True  26.00      0      0   18.7875           1
208         1       3  False  16.00      0      0    7.7500           0
209         1       1   True  40.00      0      0   31.0000           1
210         0       3   True  24.00      0      0    7.0500           0
211         1       2  False  35.00      0      0   21.0000           0
212         0       3   True  22.00      0      0    7.2500           0
213         0       2   True  30.00      0      0   13.0000           0
214         0       3   True  30.00      1      0    7.7500           0
215         1       1  False  31.00      1      0  113.2750           1
216         1       3  False  27.00      0      0    7.9250           0
217         0       2   True  42.00      1      0   27.0000           0
218         1       1  False  32.00      0      0   76.2917           1
219         0       2   True  30.00      0      0   10.5000           0
220         1       3   True  16.00      0      0    8.0500           0
221         0       2   True  27.00      0      0   13.0000           0
222         0       3   True  51.00      0      0    8.0500           0
223         0       3   True  30.00      0      0    7.8958           0
224         1       1   True  38.00      1      0   90.0000           0
225         0       3   True  22.00      0      0    9.3500           0
226         1       2   True  19.00      0      0   10.5000           0
227         0       3   True  20.50      0      0    7.2500           0
228         0       2   True  18.00      0      0   13.0000           0
229         0       3  False  30.00      3      1   25.4667           0
230         1       1  False  35.00      1      0   83.4750           0
231         0       3   True  29.00      0      0    7.7750           0
232         0       2   True  59.00      0      0   13.5000           0
233         1       3  False   5.00      4      2   31.3875           0
234         0       2   True  24.00      0      0   10.5000           0
235         0       3  False  30.00      0      0    7.5500           0
236         0       2   True  44.00      1      0   26.0000           0
237         1       2  False   8.00      0      2   26.2500           0
238         0       2   True  19.00      0      0   10.5000           0
239         0       2   True  33.00      0      0   12.2750           0
240         0       3  False  30.00      1      0   14.4542           1
241         1       3  False  30.00      1      0   15.5000           0
242         0       2   True  29.00      0      0   10.5000           0
243         0       3   True  22.00      0      0    7.1250           0
244         0       3   True  30.00      0      0    7.2250           1
245         0       1   True  44.00      2      0   90.0000           0
246         0       3  False  25.00      0      0    7.7750           0
247         1       2  False  24.00      0      2   14.5000           0
248         1       1   True  37.00      1      1   52.5542           0
249         0       2   True  54.00      1      0   26.0000           0
250         0       3   True  30.00      0      0    7.2500           0
251         0       3  False  29.00      1      1   10.4625           0
252         0       1   True  62.00      0      0   26.5500           0
253         0       3   True  30.00      1      0   16.1000           0
254         0       3  False  41.00      0      2   20.2125           0
255         1       3  False  29.00      0      2   15.2458           1
256         1       1  False  30.00      0      0   79.2000           1
257         1       1  False  30.00      0      0   86.5000           0
258         1       1  False  35.00      0      0  512.3292           1
259         1       2  False  50.00      0      1   26.0000           0
260         0       3   True  30.00      0      0    7.7500           0
261         1       3   True   3.00      4      2   31.3875           0
262         0       1   True  52.00      1      1   79.6500           0
263         0       1   True  40.00      0      0    0.0000           0
264         0       3  False  30.00      0      0    7.7500           0
265         0       2   True  36.00      0      0   10.5000           0
266         0       3   True  16.00      4      1   39.6875           0
267         1       3   True  25.00      1      0    7.7750           0
268         1       1  False  58.00      0      1  153.4625           0
269         1       1  False  35.00      0      0  135.6333           0
270         0       1   True  30.00      0      0   31.0000           0
271         1       3   True  25.00      0      0    0.0000           0
272         1       2  False  41.00      0      1   19.5000           0
273         0       1   True  37.00      0      1   29.7000           1
274         1       3  False  30.00      0      0    7.7500           0
275         1       1  False  63.00      1      0   77.9583           0

In [14]:
# we will add feature with linspace using 'Fare', less exp, mean exp, more exp
bins = df['Fare'].quantile([0, 0.25, 0.75, 1])
bin_feat = []
print(bins.iloc[3])
for i in df['Fare']:
    if i <=bins.iloc[1]:
        bin_feat.append(1)
    elif i >bins.iloc[1] and i <=bins.iloc[2]:
        bin_feat.append(2)
    elif i > bins.iloc[2]:
        bin_feat.append(3)
df['Fare_bin'] = bin_feat

512.3292

In [15]:
bin_feat = []
for i in df['Age']:
    if i<=1:
        bin_feat.append(1)
    elif i >1 and i <=5:
        bin_feat.append(2)
    elif i > 5 and i<=12:
        bin_feat.append(3)
    elif i > 12 and i <=18:
        bin_feat.append(4)
    elif i > 18 and i<=30:
        bin_feat.append(5)
    elif i > 30 and i <= 45:
        bin_feat.append(6)
    elif i > 45 and i <=60:
        bin_feat.append(7)
    elif i > 60:
        bin_feat.append(8)

df['Age_bin'] = bin_feat

In [16]:
print(df['Age'].max())
print(df['Age'])

80.0
0      22.00
1      38.00
2      26.00
3      35.00
4      35.00
5      30.00
6      54.00
7       2.00
8      27.00
9      14.00
10      4.00
11     58.00
12     20.00
13     39.00
14     14.00
15     55.00
16      2.00
17     30.00
18     31.00
19     30.00
20     35.00
21     34.00
22     15.00
23     28.00
24      8.00
25     38.00
26     30.00
27     19.00
28     30.00
29     30.00
30     40.00
31     30.00
32     30.00
33     66.00
34     28.00
35     42.00
36     30.00
37     21.00
38     18.00
39     14.00
40     40.00
41     27.00
42     30.00
43      3.00
44     19.00
45     30.00
46     30.00
47     30.00
48     30.00
49     18.00
50      7.00
51     21.00
52     49.00
53     29.00
54     65.00
55     30.00
56     21.00
57     28.50
58      5.00
59     11.00
60     22.00
61     38.00
62     45.00
63      4.00
64     30.00
65     30.00
66     29.00
67     19.00
68     17.00
69     26.00
70     32.00
71     16.00
72     21.00
73     26.00
74     32.00
75     25.00
76     30.00
77     30.00
78      0.83
79     30.00
80     22.00
81     29.00
82     30.00
83     28.00
84     17.00
85     33.00
86     16.00
87     30.00
88     23.00
89     24.00
90     29.00
91     20.00
92     46.00
93     26.00
94     59.00
95     30.00
96     71.00
97     23.00
98     34.00
99     34.00
100    28.00
101    30.00
102    21.00
103    33.00
104    37.00
105    28.00
106    21.00
107    30.00
108    38.00
109    30.00
110    47.00
111    14.50
112    22.00
113    20.00
114    17.00
115    21.00
116    70.50
117    29.00
118    24.00
119     2.00
120    21.00
121    30.00
122    32.50
123    32.50
124    54.00
125    12.00
126    30.00
127    24.00
128    30.00
129    45.00
130    33.00
131    20.00
132    47.00
133    29.00
134    25.00
135    23.00
136    19.00
137    37.00
138    16.00
139    24.00
140    30.00
141    22.00
142    24.00
143    19.00
144    18.00
145    19.00
146    27.00
147     9.00
148    36.50
149    42.00
150    51.00
151    22.00
152    55.50
153    40.50
154    30.00
155    51.00
156    16.00
157    30.00
158    30.00
159    30.00
160    44.00
161    40.00
162    26.00
163    17.00
164     1.00
165     9.00
166    30.00
167    45.00
168    30.00
169    28.00
170    61.00
171     4.00
172     1.00
173    21.00
174    56.00
175    18.00
176    30.00
177    50.00
178    30.00
179    36.00
180    30.00
181    30.00
182     9.00
183     1.00
184     4.00
185    30.00
186    30.00
187    45.00
188    40.00
189    36.00
190    32.00
191    19.00
192    19.00
193     3.00
194    44.00
195    58.00
196    30.00
197    42.00
198    30.00
199    24.00
200    28.00
201    30.00
202    34.00
203    45.50
204    18.00
205     2.00
206    32.00
207    26.00
208    16.00
209    40.00
210    24.00
211    35.00
212    22.00
213    30.00
214    30.00
215    31.00
216    27.00
217    42.00
218    32.00
219    30.00
220    16.00
221    27.00
222    51.00
223    30.00
224    38.00
225    22.00
226    19.00
227    20.50
228    18.00
229    30.00
230    35.00
231    29.00
232    59.00
233     5.00
234    24.00
235    30.00
236    44.00
237     8.00
238    19.00
239    33.00
240    30.00
241    30.00
242    29.00
243    22.00
244    30.00
245    44.00
246    25.00
247    24.00
248    37.00
249    54.00
250    30.00
251    29.00
252    62.00
253    30.00
254    41.00
255    29.00
256    30.00
257    30.00
258    35.00
259    50.00
260    30.00
261     3.00
262    52.00
263    40.00
264    30.00
265    36.00
266    16.00
267    25.00
268    58.00
269    35.00
270    30.00
271    25.00
272    41.00
273    37.00
274    30.00
275    63.00
276    45.00
277    30.00
278     7.00
279    35.00
280    65.00
281    28.00
282    16.00
283    19.00
284    30.00
285    33.00
286    30.00
287    22.00
288    42.00
289    22.00
290    26.00
291    19.00
292    36.00
293    24.00
294    24.00
295    30.00
296    23.50
297     2.00
298    30.00
299    50.00
300    30.00
301    30.00
302    19.00
303    30.00
304    30.00
305     0.92
306    30.00
307    17.00
308    30.00
309    30.00
310    24.00
311    18.00
312    26.00
313    28.00
314    43.00
315    26.00
316    24.00
317    54.00
318    31.00
319    40.00
320    22.00
321    27.00
322    30.00
323    22.00
324    30.00
325    36.00
326    61.00
327    36.00
328    31.00
329    16.00
330    30.00
331    45.50
332    38.00
333    16.00
334    30.00
335    30.00
336    29.00
337    41.00
338    45.00
339    45.00
340     2.00
341    24.00
342    28.00
343    25.00
344    36.00
345    24.00
346    40.00
347    30.00
348     3.00
349    42.00
350    23.00
351    30.00
352    15.00
353    25.00
354    30.00
355    28.00
356    22.00
357    38.00
358    30.00
359    30.00
360    40.00
361    29.00
362    45.00
363    35.00
364    30.00
365    30.00
366    60.00
367    30.00
368    30.00
369    24.00
370    25.00
371    18.00
372    19.00
373    22.00
374     3.00
375    30.00
376    22.00
377    27.00
378    20.00
379    19.00
380    42.00
381     1.00
382    32.00
383    35.00
384    30.00
385    18.00
386     1.00
387    36.00
388    30.00
389    17.00
390    36.00
391    21.00
392    28.00
393    23.00
394    24.00
395    22.00
396    31.00
397    46.00
398    23.00
399    28.00
400    39.00
401    26.00
402    21.00
403    28.00
404    20.00
405    34.00
406    51.00
407     3.00
408    21.00
409    30.00
410    30.00
411    30.00
412    33.00
413    30.00
414    44.00
415    30.00
416    34.00
417    18.00
418    30.00
419    10.00
420    30.00
421    21.00
422    29.00
423    28.00
424    18.00
425    30.00
426    28.00
427    19.00
428    30.00
429    32.00
430    28.00
431    30.00
432    42.00
433    17.00
434    50.00
435    14.00
436    21.00
437    24.00
438    64.00
439    31.00
440    45.00
441    20.00
442    25.00
443    28.00
444    30.00
445     4.00
446    13.00
447    34.00
448     5.00
449    52.00
450    36.00
451    30.00
452    30.00
453    49.00
454    30.00
455    29.00
456    65.00
457    30.00
458    50.00
459    30.00
460    48.00
461    34.00
462    47.00
463    48.00
464    30.00
465    38.00
466    30.00
467    56.00
468    30.00
469     0.75
470    30.00
471    38.00
472    33.00
473    23.00
474    22.00
475    30.00
476    34.00
477    29.00
478    22.00
479     2.00
480     9.00
481    30.00
482    50.00
483    63.00
484    25.00
485    30.00
486    35.00
487    58.00
488    30.00
489     9.00
490    30.00
491    21.00
492    55.00
493    71.00
494    21.00
495    30.00
496    54.00
497    30.00
498    25.00
499    24.00
500    17.00
501    21.00
502    30.00
503    37.00
504    16.00
505    18.00
506    33.00
507    30.00
508    28.00
509    26.00
510    29.00
511    30.00
512    36.00
513    54.00
514    24.00
515    47.00
516    34.00
517    30.00
518    36.00
519    32.00
520    30.00
521    22.00
522    30.00
523    44.00
524    30.00
525    40.50
526    50.00
527    30.00
528    39.00
529    23.00
530     2.00
531    30.00
532    17.00
533    30.00
534    30.00
535     7.00
536    45.00
537    30.00
538    30.00
539    22.00
540    36.00
541     9.00
542    11.00
543    32.00
544    50.00
545    64.00
546    19.00
547    30.00
548    33.00
549     8.00
550    17.00
551    27.00
552    30.00
553    22.00
554    22.00
555    62.00
556    48.00
557    30.00
558    39.00
559    36.00
560    30.00
561    40.00
562    28.00
563    30.00
564    30.00
565    24.00
566    19.00
567    29.00
568    30.00
569    32.00
570    62.00
571    53.00
572    36.00
573    30.00
574    16.00
575    19.00
576    34.00
577    39.00
578    30.00
579    32.00
580    25.00
581    39.00
582    54.00
583    36.00
584    30.00
585    18.00
586    47.00
587    60.00
588    22.00
589    30.00
590    35.00
591    52.00
592    47.00
593    30.00
594    37.00
595    36.00
596    30.00
597    49.00
598    30.00
599    49.00
600    24.00
601    30.00
602    30.00
603    44.00
604    35.00
605    36.00
606    30.00
607    27.00
608    22.00
609    40.00
610    39.00
611    30.00
612    30.00
613    30.00
614    35.00
615    24.00
616    34.00
617    26.00
618     4.00
619    26.00
620    27.00
621    42.00
622    20.00
623    21.00
624    21.00
625    61.00
626    57.00
627    21.00
628    26.00
629    30.00
630    80.00
631    51.00
632    32.00
633    30.00
634     9.00
635    28.00
636    32.00
637    31.00
638    41.00
639    30.00
640    20.00
641    24.00
642     2.00
643    30.00
644     0.75
645    48.00
646    19.00
647    56.00
648    30.00
649    23.00
650    30.00
651    18.00
652    21.00
653    30.00
654    18.00
655    24.00
656    30.00
657    32.00
658    23.00
659    58.00
660    50.00
661    40.00
662    47.00
663    36.00
664    20.00
665    32.00
666    25.00
667    30.00
668    43.00
669    30.00
670    40.00
671    31.00
672    70.00
673    31.00
674    30.00
675    18.00
676    24.50
677    18.00
678    43.00
679    36.00
680    30.00
681    27.00
682    20.00
683    14.00
684    60.00
685    25.00
686    14.00
687    19.00
688    18.00
689    15.00
690    31.00
691     4.00
692    30.00
693    25.00
694    60.00
695    52.00
696    44.00
697    30.00
698    49.00
699    42.00
700    18.00
701    35.00
702    18.00
703    25.00
704    26.00
705    39.00
706    45.00
707    42.00
708    22.00
709    30.00
710    24.00
711    30.00
712    48.00
713    29.00
714    52.00
715    19.00
716    38.00
717    27.00
718    30.00
719    33.00
720     6.00
721    17.00
722    34.00
723    50.00
724    27.00
725    20.00
726    30.00
727    30.00
728    25.00
729    25.00
730    29.00
731    11.00
732    30.00
733    23.00
734    23.00
735    28.50
736    48.00
737    35.00
738    30.00
739    30.00
740    30.00
741    36.00
742    21.00
743    24.00
744    31.00
745    70.00
746    16.00
747    30.00
748    19.00
749    31.00
750     4.00
751     6.00
752    33.00
753    23.00
754    48.00
755     0.67
756    28.00
757    18.00
758    34.00
759    33.00
760    30.00
761    41.00
762    20.00
763    36.00
764    16.00
765    51.00
766    30.00
767    30.50
768    30.00
769    32.00
770    24.00
771    48.00
772    57.00
773    30.00
774    54.00
775    18.00
776    30.00
777     5.00
778    30.00
779    43.00
780    13.00
781    17.00
782    29.00
783    30.00
784    25.00
785    25.00
786    18.00
787     8.00
788     1.00
789    46.00
790    30.00
791    16.00
792    30.00
793    30.00
794    25.00
795    39.00
796    49.00
797    31.00
798    30.00
799    30.00
800    34.00
801    31.00
802    11.00
803     0.42
804    27.00
805    31.00
806    39.00
807    18.00
808    39.00
809    33.00
810    26.00
811    39.00
812    35.00
813     6.00
814    30.50
815    30.00
816    23.00
817    31.00
818    43.00
819    10.00
820    52.00
821    27.00
822    38.00
823    27.00
824     2.00
825    30.00
826    30.00
827     1.00
828    30.00
829    62.00
830    15.00
831     0.83
832    30.00
833    23.00
834    18.00
835    39.00
836    21.00
837    30.00
838    32.00
839    30.00
840    20.00
841    16.00
842    30.00
843    34.50
844    17.00
845    42.00
846    30.00
847    35.00
848    28.00
849    30.00
850     4.00
851    74.00
852     9.00
853    16.00
854    44.00
855    18.00
856    45.00
857    51.00
858    24.00
859    30.00
860    41.00
861    21.00
862    48.00
863    30.00
864    24.00
865    42.00
866    27.00
867    31.00
868    30.00
869     4.00
870    26.00
871    47.00
872    33.00
873    47.00
874    28.00
875    15.00
876    20.00
877    19.00
878    30.00
879    56.00
880    25.00
881    33.00
882    22.00
883    28.00
884    25.00
885    39.00
886    27.00
887    19.00
888    30.00
889    26.00
890    32.00
Name: Age, dtype: float64

In [17]:
df.corr()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Fare_bin,Age_bin
Survived,1.000000,-0.338481,-0.543351,-0.070657,-0.035322,0.081629,0.257307,0.168240,0.003650,-0.155660,0.278828,-0.091510
Pclass,-0.338481,1.000000,0.131900,-0.329727,0.083081,0.018443,-0.549500,-0.243292,0.221009,0.081720,-0.613295,-0.304233
Sex,-0.543351,0.131900,1.000000,0.084660,-0.114631,-0.245489,-0.182333,-0.082853,-0.074115,0.125722,-0.227227,0.089058
Age,-0.070657,-0.329727,0.084660,1.000000,-0.232440,-0.180330,0.090632,0.032330,-0.010738,-0.029322,0.076585,0.934669
SibSp,-0.035322,0.083081,-0.114631,-0.232440,1.000000,0.414838,0.159651,-0.059528,-0.026354,0.070941,0.349465,-0.283585
Parch,0.081629,0.018443,-0.245489,-0.180330,0.414838,1.000000,0.216225,-0.011069,-0.081228,0.063036,0.339821,-0.246679
Fare,0.257307,-0.549500,-0.182333,0.090632,0.159651,0.216225,1.000000,0.269335,-0.117216,-0.166603,0.580370,0.083779
Embarked_C,0.168240,-0.243292,-0.082853,0.032330,-0.059528,-0.011069,0.269335,1.000000,-0.148258,-0.778359,0.163169,0.004829
Embarked_Q,0.003650,0.221009,-0.074115,-0.010738,-0.026354,-0.081228,-0.117216,-0.148258,1.000000,-0.496624,-0.276459,-0.036151
Embarked_S,-0.155660,0.081720,0.125722,-0.029322,0.070941,0.063036,-0.166603,-0.778359,-0.496624,1.000000,0.023852,0.011097
Fare_bin,0.278828,-0.613295,-0.227227,0.076585,0.349465,0.339821,0.580370,0.163169,-0.276459,0.023852,1.000000,0.038831
Age_bin,-0.091510,-0.304233,0.089058,0.934669,-0.283585,-0.246679,0.083779,0.004829,-0.036151,0.011097,0.038831,1.000000

In [18]:
p_values = []
p_coefs = []
for i in df.columns:
    print(i)
    p_value, p_coef = stats.pearsonr(df[i], df[target])
    
    p_values.append(p_value)
    p_coefs.append(p_coef)

pearson = pd.DataFrame({'columns':df.columns, 'p_values':p_values, 'p_coefs':p_coefs})
pearson

Survived
Pclass
Sex
Age
SibSp
Parch
Fare
Embarked_C
Embarked_Q
Embarked_S
Fare_bin
Age_bin

       columns  p_values       p_coefs
0     Survived  1.000000  0.000000e+00
1       Pclass -0.338481  2.537047e-25
2          Sex -0.543351  1.406066e-69
3          Age -0.070657  3.496470e-02
4        SibSp -0.035322  2.922439e-01
5        Parch  0.081629  1.479925e-02
6         Fare  0.257307  6.120189e-15
7   Embarked_C  0.168240  4.397151e-07
8   Embarked_Q  0.003650  9.133532e-01
9   Embarked_S -0.155660  3.036111e-06
10    Fare_bin  0.278828  2.252872e-17
11     Age_bin -0.091510  6.267722e-03

In [19]:
features = [i for i in df.columns if i!='Survived']
#features.remove('Embarked_Q')
#features.remove('SibSp')
#features.remove('Age')
#features.remove('Age_bin')
#features.remove('Parch')

In [20]:
train_set = df[:700]
valid_set = df[700:800]
test_set = df[800:]

In [21]:
x_train, y_train = df[features], df[target]
x_valid, y_valid = df[features], df[target]
x_test, y_test = df[features], df[target]

In [22]:
#best_param = grid.best_params_
#print(best_param)
model = DecisionTreeClassifier(max_leaf_nodes=8, max_depth=5)
model.fit(x_train, y_train)
pred_valid = model.predict(x_valid)
pred_test = model.predict(x_test)

In [23]:
accuracy_score(pred_valid, y_valid)

0.8327721661054994

In [24]:
accuracy_score(pred_test, y_test)

0.8327721661054994

In [25]:
print(test.info())
print(test['Age'].max())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.0+ KB
None
76.0

In [26]:
# fill the na in Fare column and Age
test['Fare'] = test['Fare'].fillna(np.mean(test['Fare']))
test['Age'] = test['Age'].fillna(round(np.mean(test['Age'])))

In [27]:
test.corr()

             PassengerId    Pclass       Age     SibSp     Parch      Fare
PassengerId     1.000000 -0.026751 -0.030935  0.003818  0.043080  0.008209
Pclass         -0.026751  1.000000 -0.443234  0.001087  0.018721 -0.576619
Age            -0.030935 -0.443234  1.000000 -0.078870 -0.044980  0.328429
SibSp           0.003818  0.001087 -0.078870  1.000000  0.306895  0.171488
Parch           0.043080  0.018721 -0.044980  0.306895  1.000000  0.230001
Fare            0.008209 -0.576619  0.328429  0.171488  0.230001  1.000000

In [28]:
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50,0,0,330911,7.829200,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00,1,0,363272,7.000000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00,0,0,240276,9.687500,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00,0,0,315154,8.662500,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00,1,1,3101298,12.287500,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.00,0,0,7538,9.225000,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.00,0,0,330972,7.629200,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.00,1,1,248738,29.000000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00,0,0,2657,7.229200,NaN,C
9,901,3,"Davies, Mr. John Samuel",male,21.00,2,0,A/4 48871,24.150000,NaN,S
10,902,3,"Ilieff, Mr. Ylio",male,30.00,0,0,349220,7.895800,NaN,S
11,903,1,"Jones, Mr. Charles Cresson",male,46.00,0,0,694,26.000000,NaN,S
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.00,1,0,21228,82.266700,B45,S
13,905,2,"Howard, Mr. Benjamin",male,63.00,1,0,24065,26.000000,NaN,S
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.00,1,0,W.E.P. 5734,61.175000,E31,S
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.00,1,0,SC/PARIS 2167,27.720800,NaN,C
16,908,2,"Keane, Mr. Daniel",male,35.00,0,0,233734,12.350000,NaN,Q
17,909,3,"Assaf, Mr. Gerios",male,21.00,0,0,2692,7.225000,NaN,C
18,910,3,"Ilmakangas, Miss. Ida Livija",female,27.00,1,0,STON/O2. 3101270,7.925000,NaN,S
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.00,0,0,2696,7.225000,NaN,C
20,912,1,"Rothschild, Mr. Martin",male,55.00,1,0,PC 17603,59.400000,NaN,C
21,913,3,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.170800,NaN,S
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,30.00,0,0,PC 17598,31.683300,NaN,S
23,915,1,"Williams, Mr. Richard Norris II",male,21.00,0,1,PC 17597,61.379200,NaN,C
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.00,1,3,PC 17608,262.375000,B57 B59 B63 B66,C
25,917,3,"Robins, Mr. Alexander A",male,50.00,1,0,A/5. 3337,14.500000,NaN,S
26,918,1,"Ostby, Miss. Helene Ragnhild",female,22.00,0,1,113509,61.979200,B36,C
27,919,3,"Daher, Mr. Shedid",male,22.50,0,0,2698,7.225000,NaN,C
28,920,1,"Brady, Mr. John Bertram",male,41.00,0,0,113054,30.500000,A21,S
29,921,3,"Samaan, Mr. Elias",male,30.00,2,0,2662,21.679200,NaN,C
30,922,2,"Louch, Mr. Charles Alexander",male,50.00,1,0,SC/AH 3085,26.000000,NaN,S
31,923,2,"Jefferys, Mr. Clifford Thomas",male,24.00,2,0,C.A. 31029,31.500000,NaN,S
32,924,3,"Dean, Mrs. Bertram (Eva Georgetta Light)",female,33.00,1,2,C.A. 2315,20.575000,NaN,S
33,925,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,30.00,1,2,W./C. 6607,23.450000,NaN,S
34,926,1,"Mock, Mr. Philipp Edmund",male,30.00,1,0,13236,57.750000,C78,C
35,927,3,"Katavelas, Mr. Vassilios (Catavelas Vassilios"")""",male,18.50,0,0,2682,7.229200,NaN,C
36,928,3,"Roth, Miss. Sarah A",female,30.00,0,0,342712,8.050000,NaN,S
37,929,3,"Cacic, Miss. Manda",female,21.00,0,0,315087,8.662500,NaN,S
38,930,3,"Sap, Mr. Julius",male,25.00,0,0,345768,9.500000,NaN,S
39,931,3,"Hee, Mr. Ling",male,30.00,0,0,1601,56.495800,NaN,S
40,932,3,"Karun, Mr. Franz",male,39.00,0,1,349256,13.416700,NaN,C
41,933,1,"Franklin, Mr. Thomas Parham",male,30.00,0,0,113778,26.550000,D34,S
42,934,3,"Goldsmith, Mr. Nathan",male,41.00,0,0,SOTON/O.Q. 3101263,7.850000,NaN,S
43,935,2,"Corbett, Mrs. Walter H (Irene Colvin)",female,30.00,0,0,237249,13.000000,NaN,S
44,936,1,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",female,45.00,1,0,11753,52.554200,D19,S
45,937,3,"Peltomaki, Mr. Nikolai Johannes",male,25.00,0,0,STON/O 2. 3101291,7.925000,NaN,S
46,938,1,"Chevre, Mr. Paul Romaine",male,45.00,0,0,PC 17594,29.700000,A9,C
47,939,3,"Shaughnessy, Mr. Patrick",male,30.00,0,0,370374,7.750000,NaN,Q
48,940,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.00,0,0,11813,76.291700,D15,C
49,941,3,"Coutts, Mrs. William (Winnie Minnie"" Treanor)""",female,36.00,0,2,C.A. 37671,15.900000,NaN,S
50,942,1,"Smith, Mr. Lucien Philip",male,24.00,1,0,13695,60.000000,C31,S
51,943,2,"Pulbaum, Mr. Franz",male,27.00,0,0,SC/PARIS 2168,15.033300,NaN,C
52,944,2,"Hocking, Miss. Ellen Nellie""""",female,20.00,2,1,29105,23.000000,NaN,S
53,945,1,"Fortune, Miss. Ethel Flora",female,28.00,3,2,19950,263.000000,C23 C25 C27,S
54,946,2,"Mangiavacchi, Mr. Serafino Emilio",male,30.00,0,0,SC/A.3 2861,15.579200,NaN,C
55,947,3,"Rice, Master. Albert",male,10.00,4,1,382652,29.125000,NaN,Q
56,948,3,"Cor, Mr. Bartol",male,35.00,0,0,349230,7.895800,NaN,S
57,949,3,"Abelseth, Mr. Olaus Jorgensen",male,25.00,0,0,348122,7.650000,F G63,S
58,950,3,"Davison, Mr. Thomas Henry",male,30.00,1,0,386525,16.100000,NaN,S
59,951,1,"Chaudanson, Miss. Victorine",female,36.00,0,0,PC 17608,262.375000,B61,C
60,952,3,"Dika, Mr. Mirko",male,17.00,0,0,349232,7.895800,NaN,S
61,953,2,"McCrae, Mr. Arthur Gordon",male,32.00,0,0,237216,13.500000,NaN,S
62,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.00,0,0,347090,7.750000,NaN,S
63,955,3,"Bradley, Miss. Bridget Delia",female,22.00,0,0,334914,7.725000,NaN,Q
64,956,1,"Ryerson, Master. John Borie",male,13.00,2,2,PC 17608,262.375000,B57 B59 B63 B66,C
65,957,2,"Corey, Mrs. Percy C (Mary Phyllis Elizabeth Mi...",female,30.00,0,0,F.C.C. 13534,21.000000,NaN,S
66,958,3,"Burns, Miss. Mary Delia",female,18.00,0,0,330963,7.879200,NaN,Q
67,959,1,"Moore, Mr. Clarence Bloomfield",male,47.00,0,0,113796,42.400000,NaN,S
68,960,1,"Tucker, Mr. Gilbert Milligan Jr",male,31.00,0,0,2543,28.537500,C53,C
69,961,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.00,1,4,19950,263.000000,C23 C25 C27,S
70,962,3,"Mulvihill, Miss. Bertha E",female,24.00,0,0,382653,7.750000,NaN,Q
71,963,3,"Minkoff, Mr. Lazar",male,21.00,0,0,349211,7.895800,NaN,S
72,964,3,"Nieminen, Miss. Manta Josefina",female,29.00,0,0,3101297,7.925000,NaN,S
73,965,1,"Ovies y Rodriguez, Mr. Servando",male,28.50,0,0,PC 17562,27.720800,D43,C
74,966,1,"Geiger, Miss. Amalie",female,35.00,0,0,113503,211.500000,C130,C
75,967,1,"Keeping, Mr. Edwin",male,32.50,0,0,113503,211.500000,C132,C
76,968,3,"Miles, Mr. Frank",male,30.00,0,0,359306,8.050000,NaN,S
77,969,1,"Cornell, Mrs. Robert Clifford (Malvina Helen L...",female,55.00,2,0,11770,25.700000,C101,S
78,970,2,"Aldworth, Mr. Charles Augustus",male,30.00,0,0,248744,13.000000,NaN,S
79,971,3,"Doyle, Miss. Elizabeth",female,24.00,0,0,368702,7.750000,NaN,Q
80,972,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.245800,NaN,C
81,973,1,"Straus, Mr. Isidor",male,67.00,1,0,PC 17483,221.779200,C55 C57,S
82,974,1,"Case, Mr. Howard Brown",male,49.00,0,0,19924,26.000000,NaN,S
83,975,3,"Demetri, Mr. Marinko",male,30.00,0,0,349238,7.895800,NaN,S
84,976,2,"Lamb, Mr. John Joseph",male,30.00,0,0,240261,10.708300,NaN,Q
85,977,3,"Khalil, Mr. Betros",male,30.00,1,0,2660,14.454200,NaN,C
86,978,3,"Barry, Miss. Julia",female,27.00,0,0,330844,7.879200,NaN,Q
87,979,3,"Badman, Miss. Emily Louisa",female,18.00,0,0,A/4 31416,8.050000,NaN,S
88,980,3,"O'Donoghue, Ms. Bridget",female,30.00,0,0,364856,7.750000,NaN,Q
89,981,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.000000,NaN,S
90,982,3,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.00,1,0,347072,13.900000,NaN,S
91,983,3,"Pedersen, Mr. Olaf",male,30.00,0,0,345498,7.775000,NaN,S
92,984,1,"Davidson, Mrs. Thornton (Orian Hays)",female,27.00,1,2,F.C. 12750,52.000000,B71,S
93,985,3,"Guest, Mr. Robert",male,30.00,0,0,376563,8.050000,NaN,S
94,986,1,"Birnbaum, Mr. Jakob",male,25.00,0,0,13905,26.000000,NaN,C
95,987,3,"Tenglin, Mr. Gunnar Isidor",male,25.00,0,0,350033,7.795800,NaN,S
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.00,1,0,19877,78.850000,C46,S
97,989,3,"Makinen, Mr. Kalle Edvard",male,29.00,0,0,STON/O 2. 3101268,7.925000,NaN,S
98,990,3,"Braf, Miss. Elin Ester Maria",female,20.00,0,0,347471,7.854200,NaN,S
99,991,3,"Nancarrow, Mr. William Henry",male,33.00,0,0,A./5. 3338,8.050000,NaN,S
100,992,1,"Stengel, Mrs. Charles Emil Henry (Annie May Mo...",female,43.00,1,0,11778,55.441700,C116,C
101,993,2,"Weisz, Mr. Leopold",male,27.00,1,0,228414,26.000000,NaN,S
102,994,3,"Foley, Mr. William",male,30.00,0,0,365235,7.750000,NaN,Q
103,995,3,"Johansson Palmquist, Mr. Oskar Leander",male,26.00,0,0,347070,7.775000,NaN,S
104,996,3,"Thomas, Mrs. Alexander (Thamine Thelma"")""",female,16.00,1,1,2625,8.516700,NaN,C
105,997,3,"Holthen, Mr. Johan Martin",male,28.00,0,0,C 4001,22.525000,NaN,S
106,998,3,"Buckley, Mr. Daniel",male,21.00,0,0,330920,7.820800,NaN,Q
107,999,3,"Ryan, Mr. Edward",male,30.00,0,0,383162,7.750000,NaN,Q
108,1000,3,"Willer, Mr. Aaron (Abi Weller"")""",male,30.00,0,0,3410,8.712500,NaN,S
109,1001,2,"Swane, Mr. George",male,18.50,0,0,248734,13.000000,F,S
110,1002,2,"Stanton, Mr. Samuel Ward",male,41.00,0,0,237734,15.045800,NaN,C
111,1003,3,"Shine, Miss. Ellen Natalia",female,30.00,0,0,330968,7.779200,NaN,Q
112,1004,1,"Evans, Miss. Edith Corse",female,36.00,0,0,PC 17531,31.679200,A29,C
113,1005,3,"Buckley, Miss. Katherine",female,18.50,0,0,329944,7.283300,NaN,Q
114,1006,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.00,1,0,PC 17483,221.779200,C55 C57,S
115,1007,3,"Chronopoulos, Mr. Demetrios",male,18.00,1,0,2680,14.454200,NaN,C
116,1008,3,"Thomas, Mr. John",male,30.00,0,0,2681,6.437500,NaN,C
117,1009,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.700000,G6,S
118,1010,1,"Beattie, Mr. Thomson",male,36.00,0,0,13050,75.241700,C6,C
119,1011,2,"Chapman, Mrs. John Henry (Sara Elizabeth Lawry)",female,29.00,1,0,SC/AH 29037,26.000000,NaN,S
120,1012,2,"Watt, Miss. Bertha J",female,12.00,0,0,C.A. 33595,15.750000,NaN,S
121,1013,3,"Kiernan, Mr. John",male,30.00,1,0,367227,7.750000,NaN,Q
122,1014,1,"Schabert, Mrs. Paul (Emma Mock)",female,35.00,1,0,13236,57.750000,C28,C
123,1015,3,"Carver, Mr. Alfred John",male,28.00,0,0,392095,7.250000,NaN,S
124,1016,3,"Kennedy, Mr. John",male,30.00,0,0,368783,7.750000,NaN,Q
125,1017,3,"Cribb, Miss. Laura Alice",female,17.00,0,1,371362,16.100000,NaN,S
126,1018,3,"Brobeck, Mr. Karl Rudolf",male,22.00,0,0,350045,7.795800,NaN,S
127,1019,3,"McCoy, Miss. Alicia",female,30.00,2,0,367226,23.250000,NaN,Q
128,1020,2,"Bowenur, Mr. Solomon",male,42.00,0,0,211535,13.000000,NaN,S
129,1021,3,"Petersen, Mr. Marius",male,24.00,0,0,342441,8.050000,NaN,S
130,1022,3,"Spinner, Mr. Henry John",male,32.00,0,0,STON/OQ. 369943,8.050000,NaN,S
131,1023,1,"Gracie, Col. Archibald IV",male,53.00,0,0,113780,28.500000,C51,C
132,1024,3,"Lefebre, Mrs. Frank (Frances)",female,30.00,0,4,4133,25.466700,NaN,S
133,1025,3,"Thomas, Mr. Charles P",male,30.00,1,0,2621,6.437500,NaN,C
134,1026,3,"Dintcheff, Mr. Valtcho",male,43.00,0,0,349226,7.895800,NaN,S
135,1027,3,"Carlsson, Mr. Carl Robert",male,24.00,0,0,350409,7.854200,NaN,S
136,1028,3,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.225000,NaN,C
137,1029,2,"Schmidt, Mr. August",male,26.00,0,0,248659,13.000000,NaN,S
138,1030,3,"Drapkin, Miss. Jennie",female,23.00,0,0,SOTON/OQ 392083,8.050000,NaN,S
139,1031,3,"Goodwin, Mr. Charles Frederick",male,40.00,1,6,CA 2144,46.900000,NaN,S
140,1032,3,"Goodwin, Miss. Jessie Allis",female,10.00,5,2,CA 2144,46.900000,NaN,S
141,1033,1,"Daniels, Miss. Sarah",female,33.00,0,0,113781,151.550000,NaN,S
142,1034,1,"Ryerson, Mr. Arthur Larned",male,61.00,1,3,PC 17608,262.375000,B57 B59 B63 B66,C
143,1035,2,"Beauchamp, Mr. Henry James",male,28.00,0,0,244358,26.000000,NaN,S
144,1036,1,"Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lin...",male,42.00,0,0,17475,26.550000,NaN,S
145,1037,3,"Vander Planke, Mr. Julius",male,31.00,3,0,345763,18.000000,NaN,S
146,1038,1,"Hilliard, Mr. Herbert Henry",male,30.00,0,0,17463,51.862500,E46,S
147,1039,3,"Davies, Mr. Evan",male,22.00,0,0,SC/A4 23568,8.050000,NaN,S
148,1040,1,"Crafton, Mr. John Bertram",male,30.00,0,0,113791,26.550000,NaN,S
149,1041,2,"Lahtinen, Rev. William",male,30.00,1,1,250651,26.000000,NaN,S
150,1042,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23.00,0,1,11767,83.158300,C54,C
151,1043,3,"Matinoff, Mr. Nicola",male,30.00,0,0,349255,7.895800,NaN,C
152,1044,3,"Storey, Mr. Thomas",male,60.50,0,0,3701,35.627188,NaN,S
153,1045,3,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36.00,0,2,350405,12.183300,NaN,S
154,1046,3,"Asplund, Master. Filip Oscar",male,13.00,4,2,347077,31.387500,NaN,S
155,1047,3,"Duquemin, Mr. Joseph",male,24.00,0,0,S.O./P.P. 752,7.550000,NaN,S
156,1048,1,"Bird, Miss. Ellen",female,29.00,0,0,PC 17483,221.779200,C97,S
157,1049,3,"Lundin, Miss. Olga Elida",female,23.00,0,0,347469,7.854200,NaN,S
158,1050,1,"Borebank, Mr. John James",male,42.00,0,0,110489,26.550000,D22,S
159,1051,3,"Peacock, Mrs. Benjamin (Edith Nile)",female,26.00,0,2,SOTON/O.Q. 3101315,13.775000,NaN,S
160,1052,3,"Smyth, Miss. Julia",female,30.00,0,0,335432,7.733300,NaN,Q
161,1053,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.245800,NaN,C
162,1054,2,"Wright, Miss. Marion",female,26.00,0,0,220844,13.500000,NaN,S
163,1055,3,"Pearce, Mr. Ernest",male,30.00,0,0,343271,7.000000,NaN,S
164,1056,2,"Peruschitz, Rev. Joseph Maria",male,41.00,0,0,237393,13.000000,NaN,S
165,1057,3,"Kink-Heilmann, Mrs. Anton (Luise Heilmann)",female,26.00,1,1,315153,22.025000,NaN,S
166,1058,1,"Brandeis, Mr. Emil",male,48.00,0,0,PC 17591,50.495800,B10,C
167,1059,3,"Ford, Mr. Edward Watson",male,18.00,2,2,W./C. 6608,34.375000,NaN,S
168,1060,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,30.00,0,0,17770,27.720800,NaN,C
169,1061,3,"Hellstrom, Miss. Hilda Maria",female,22.00,0,0,7548,8.962500,NaN,S
170,1062,3,"Lithman, Mr. Simon",male,30.00,0,0,S.O./P.P. 251,7.550000,NaN,S
171,1063,3,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.225000,NaN,C
172,1064,3,"Dyker, Mr. Adolf Fredrik",male,23.00,1,0,347072,13.900000,NaN,S
173,1065,3,"Torfa, Mr. Assad",male,30.00,0,0,2673,7.229200,NaN,C
174,1066,3,"Asplund, Mr. Carl Oscar Vilhelm Gustafsson",male,40.00,1,5,347077,31.387500,NaN,S
175,1067,2,"Brown, Miss. Edith Eileen",female,15.00,0,2,29750,39.000000,NaN,S
176,1068,2,"Sincock, Miss. Maude",female,20.00,0,0,C.A. 33112,36.750000,NaN,S
177,1069,1,"Stengel, Mr. Charles Emil Henry",male,54.00,1,0,11778,55.441700,C116,C
178,1070,2,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.00,0,3,230136,39.000000,F4,S
179,1071,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.00,0,2,PC 17756,83.158300,E45,C
180,1072,2,"McCrie, Mr. James Matthew",male,30.00,0,0,233478,13.000000,NaN,S
181,1073,1,"Compton, Mr. Alexander Taylor Jr",male,37.00,1,1,PC 17756,83.158300,E52,C
182,1074,1,"Marvin, Mrs. Daniel Warner (Mary Graham Carmic...",female,18.00,1,0,113773,53.100000,D30,S
183,1075,3,"Lane, Mr. Patrick",male,30.00,0,0,7935,7.750000,NaN,Q
184,1076,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",female,27.00,1,1,PC 17558,247.520800,B58 B60,C
185,1077,2,"Maybery, Mr. Frank Hubert",male,40.00,0,0,239059,16.000000,NaN,S
186,1078,2,"Phillips, Miss. Alice Frances Louisa",female,21.00,0,1,S.O./P.P. 2,21.000000,NaN,S
187,1079,3,"Davies, Mr. Joseph",male,17.00,2,0,A/4 48873,8.050000,NaN,S
188,1080,3,"Sage, Miss. Ada",female,30.00,8,2,CA. 2343,69.550000,NaN,S
189,1081,2,"Veal, Mr. James",male,40.00,0,0,28221,13.000000,NaN,S
190,1082,2,"Angle, Mr. William A",male,34.00,1,0,226875,26.000000,NaN,S
191,1083,1,"Salomon, Mr. Abraham L",male,30.00,0,0,111163,26.000000,NaN,S
192,1084,3,"van Billiard, Master. Walter John",male,11.50,1,1,A/5. 851,14.500000,NaN,S
193,1085,2,"Lingane, Mr. John",male,61.00,0,0,235509,12.350000,NaN,Q
194,1086,2,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.500000,NaN,S
195,1087,3,"Karlsson, Mr. Julius Konrad Eugen",male,33.00,0,0,347465,7.854200,NaN,S
196,1088,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.500000,E34,C
197,1089,3,"Nilsson, Miss. Berta Olivia",female,18.00,0,0,347066,7.775000,NaN,S
198,1090,2,"Baimbrigge, Mr. Charles Robert",male,23.00,0,0,C.A. 31030,10.500000,NaN,S
199,1091,3,"Rasmussen, Mrs. (Lena Jacobsen Solvang)",female,30.00,0,0,65305,8.112500,NaN,S
200,1092,3,"Murphy, Miss. Nora",female,30.00,0,0,36568,15.500000,NaN,Q
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.400000,NaN,S
202,1094,1,"Astor, Col. John Jacob",male,47.00,1,0,PC 17757,227.525000,C62 C64,C
203,1095,2,"Quick, Miss. Winifred Vera",female,8.00,1,1,26360,26.000000,NaN,S
204,1096,2,"Andrew, Mr. Frank Thomas",male,25.00,0,0,C.A. 34050,10.500000,NaN,S
205,1097,1,"Omont, Mr. Alfred Fernand",male,30.00,0,0,F.C. 12998,25.741700,NaN,C
206,1098,3,"McGowan, Miss. Katherine",female,35.00,0,0,9232,7.750000,NaN,Q
207,1099,2,"Collett, Mr. Sidney C Stuart",male,24.00,0,0,28034,10.500000,NaN,S
208,1100,1,"Rosenbaum, Miss. Edith Louise",female,33.00,0,0,PC 17613,27.720800,A11,C
209,1101,3,"Delalic, Mr. Redjo",male,25.00,0,0,349250,7.895800,NaN,S
210,1102,3,"Andersen, Mr. Albert Karvin",male,32.00,0,0,C 4001,22.525000,NaN,S
211,1103,3,"Finoli, Mr. Luigi",male,30.00,0,0,SOTON/O.Q. 3101308,7.050000,NaN,S
212,1104,2,"Deacon, Mr. Percy William",male,17.00,0,0,S.O.C. 14879,73.500000,NaN,S
213,1105,2,"Howard, Mrs. Benjamin (Ellen Truelove Arman)",female,60.00,1,0,24065,26.000000,NaN,S
214,1106,3,"Andersson, Miss. Ida Augusta Margareta",female,38.00,4,2,347091,7.775000,NaN,S
215,1107,1,"Head, Mr. Christopher",male,42.00,0,0,113038,42.500000,B11,S
216,1108,3,"Mahon, Miss. Bridget Delia",female,30.00,0,0,330924,7.879200,NaN,Q
217,1109,1,"Wick, Mr. George Dennick",male,57.00,1,1,36928,164.866700,NaN,S
218,1110,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.00,1,1,113503,211.500000,C80,C
219,1111,3,"Thomson, Mr. Alexander Morrison",male,30.00,0,0,32302,8.050000,NaN,S
220,1112,2,"Duran y More, Miss. Florentina",female,30.00,1,0,SC/PARIS 2148,13.858300,NaN,C
221,1113,3,"Reynolds, Mr. Harold J",male,21.00,0,0,342684,8.050000,NaN,S
222,1114,2,"Cook, Mrs. (Selena Rogers)",female,22.00,0,0,W./C. 14266,10.500000,F33,S
223,1115,3,"Karlsson, Mr. Einar Gervasius",male,21.00,0,0,350053,7.795800,NaN,S
224,1116,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.00,0,0,PC 17606,27.445800,NaN,C
225,1117,3,"Moubarek, Mrs. George (Omine Amenia"" Alexander)""",female,30.00,0,2,2661,15.245800,NaN,C
226,1118,3,"Asplund, Mr. Johan Charles",male,23.00,0,0,350054,7.795800,NaN,S
227,1119,3,"McNeill, Miss. Bridget",female,30.00,0,0,370368,7.750000,NaN,Q
228,1120,3,"Everett, Mr. Thomas James",male,40.50,0,0,C.A. 6212,15.100000,NaN,S
229,1121,2,"Hocking, Mr. Samuel James Metcalfe",male,36.00,0,0,242963,13.000000,NaN,S
230,1122,2,"Sweet, Mr. George Frederick",male,14.00,0,0,220845,65.000000,NaN,S
231,1123,1,"Willard, Miss. Constance",female,21.00,0,0,113795,26.550000,NaN,S
232,1124,3,"Wiklund, Mr. Karl Johan",male,21.00,1,0,3101266,6.495800,NaN,S
233,1125,3,"Linehan, Mr. Michael",male,30.00,0,0,330971,7.879200,NaN,Q
234,1126,1,"Cumings, Mr. John Bradley",male,39.00,1,0,PC 17599,71.283300,C85,C
235,1127,3,"Vendel, Mr. Olof Edvin",male,20.00,0,0,350416,7.854200,NaN,S
236,1128,1,"Warren, Mr. Frank Manley",male,64.00,1,0,110813,75.250000,D37,C
237,1129,3,"Baccos, Mr. Raffull",male,20.00,0,0,2679,7.225000,NaN,C
238,1130,2,"Hiltunen, Miss. Marta",female,18.00,1,1,250650,13.000000,NaN,S
239,1131,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",female,48.00,1,0,PC 17761,106.425000,C86,C
240,1132,1,"Lindstrom, Mrs. Carl Johan (Sigrid Posse)",female,55.00,0,0,112377,27.720800,NaN,C
241,1133,2,"Christy, Mrs. (Alice Frances)",female,45.00,0,2,237789,30.000000,NaN,S
242,1134,1,"Spedden, Mr. Frederic Oakley",male,45.00,1,1,16966,134.500000,E34,C
243,1135,3,"Hyman, Mr. Abraham",male,30.00,0,0,3470,7.887500,NaN,S
244,1136,3,"Johnston, Master. William Arthur Willie""""",male,30.00,1,2,W./C. 6607,23.450000,NaN,S
245,1137,1,"Kenyon, Mr. Frederick R",male,41.00,1,0,17464,51.862500,D21,S
246,1138,2,"Karnes, Mrs. J Frank (Claire Bennett)",female,22.00,0,0,F.C.C. 13534,21.000000,NaN,S
247,1139,2,"Drew, Mr. James Vivian",male,42.00,1,1,28220,32.500000,NaN,S
248,1140,2,"Hold, Mrs. Stephen (Annie Margaret Hill)",female,29.00,1,0,26707,26.000000,NaN,S

In [29]:
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.50,0,0,330911,7.829200,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00,1,0,363272,7.000000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.00,0,0,240276,9.687500,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.00,0,0,315154,8.662500,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00,1,1,3101298,12.287500,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.00,0,0,7538,9.225000,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.00,0,0,330972,7.629200,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.00,1,1,248738,29.000000,NaN,S
8,900,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00,0,0,2657,7.229200,NaN,C
9,901,3,"Davies, Mr. John Samuel",male,21.00,2,0,A/4 48871,24.150000,NaN,S
10,902,3,"Ilieff, Mr. Ylio",male,30.00,0,0,349220,7.895800,NaN,S
11,903,1,"Jones, Mr. Charles Cresson",male,46.00,0,0,694,26.000000,NaN,S
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.00,1,0,21228,82.266700,B45,S
13,905,2,"Howard, Mr. Benjamin",male,63.00,1,0,24065,26.000000,NaN,S
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.00,1,0,W.E.P. 5734,61.175000,E31,S
15,907,2,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.00,1,0,SC/PARIS 2167,27.720800,NaN,C
16,908,2,"Keane, Mr. Daniel",male,35.00,0,0,233734,12.350000,NaN,Q
17,909,3,"Assaf, Mr. Gerios",male,21.00,0,0,2692,7.225000,NaN,C
18,910,3,"Ilmakangas, Miss. Ida Livija",female,27.00,1,0,STON/O2. 3101270,7.925000,NaN,S
19,911,3,"Assaf Khalil, Mrs. Mariana (Miriam"")""",female,45.00,0,0,2696,7.225000,NaN,C
20,912,1,"Rothschild, Mr. Martin",male,55.00,1,0,PC 17603,59.400000,NaN,C
21,913,3,"Olsen, Master. Artur Karl",male,9.00,0,1,C 17368,3.170800,NaN,S
22,914,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,30.00,0,0,PC 17598,31.683300,NaN,S
23,915,1,"Williams, Mr. Richard Norris II",male,21.00,0,1,PC 17597,61.379200,NaN,C
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.00,1,3,PC 17608,262.375000,B57 B59 B63 B66,C
25,917,3,"Robins, Mr. Alexander A",male,50.00,1,0,A/5. 3337,14.500000,NaN,S
26,918,1,"Ostby, Miss. Helene Ragnhild",female,22.00,0,1,113509,61.979200,B36,C
27,919,3,"Daher, Mr. Shedid",male,22.50,0,0,2698,7.225000,NaN,C
28,920,1,"Brady, Mr. John Bertram",male,41.00,0,0,113054,30.500000,A21,S
29,921,3,"Samaan, Mr. Elias",male,30.00,2,0,2662,21.679200,NaN,C
30,922,2,"Louch, Mr. Charles Alexander",male,50.00,1,0,SC/AH 3085,26.000000,NaN,S
31,923,2,"Jefferys, Mr. Clifford Thomas",male,24.00,2,0,C.A. 31029,31.500000,NaN,S
32,924,3,"Dean, Mrs. Bertram (Eva Georgetta Light)",female,33.00,1,2,C.A. 2315,20.575000,NaN,S
33,925,3,"Johnston, Mrs. Andrew G (Elizabeth Lily"" Watson)""",female,30.00,1,2,W./C. 6607,23.450000,NaN,S
34,926,1,"Mock, Mr. Philipp Edmund",male,30.00,1,0,13236,57.750000,C78,C
35,927,3,"Katavelas, Mr. Vassilios (Catavelas Vassilios"")""",male,18.50,0,0,2682,7.229200,NaN,C
36,928,3,"Roth, Miss. Sarah A",female,30.00,0,0,342712,8.050000,NaN,S
37,929,3,"Cacic, Miss. Manda",female,21.00,0,0,315087,8.662500,NaN,S
38,930,3,"Sap, Mr. Julius",male,25.00,0,0,345768,9.500000,NaN,S
39,931,3,"Hee, Mr. Ling",male,30.00,0,0,1601,56.495800,NaN,S
40,932,3,"Karun, Mr. Franz",male,39.00,0,1,349256,13.416700,NaN,C
41,933,1,"Franklin, Mr. Thomas Parham",male,30.00,0,0,113778,26.550000,D34,S
42,934,3,"Goldsmith, Mr. Nathan",male,41.00,0,0,SOTON/O.Q. 3101263,7.850000,NaN,S
43,935,2,"Corbett, Mrs. Walter H (Irene Colvin)",female,30.00,0,0,237249,13.000000,NaN,S
44,936,1,"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)",female,45.00,1,0,11753,52.554200,D19,S
45,937,3,"Peltomaki, Mr. Nikolai Johannes",male,25.00,0,0,STON/O 2. 3101291,7.925000,NaN,S
46,938,1,"Chevre, Mr. Paul Romaine",male,45.00,0,0,PC 17594,29.700000,A9,C
47,939,3,"Shaughnessy, Mr. Patrick",male,30.00,0,0,370374,7.750000,NaN,Q
48,940,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.00,0,0,11813,76.291700,D15,C
49,941,3,"Coutts, Mrs. William (Winnie Minnie"" Treanor)""",female,36.00,0,2,C.A. 37671,15.900000,NaN,S
50,942,1,"Smith, Mr. Lucien Philip",male,24.00,1,0,13695,60.000000,C31,S
51,943,2,"Pulbaum, Mr. Franz",male,27.00,0,0,SC/PARIS 2168,15.033300,NaN,C
52,944,2,"Hocking, Miss. Ellen Nellie""""",female,20.00,2,1,29105,23.000000,NaN,S
53,945,1,"Fortune, Miss. Ethel Flora",female,28.00,3,2,19950,263.000000,C23 C25 C27,S
54,946,2,"Mangiavacchi, Mr. Serafino Emilio",male,30.00,0,0,SC/A.3 2861,15.579200,NaN,C
55,947,3,"Rice, Master. Albert",male,10.00,4,1,382652,29.125000,NaN,Q
56,948,3,"Cor, Mr. Bartol",male,35.00,0,0,349230,7.895800,NaN,S
57,949,3,"Abelseth, Mr. Olaus Jorgensen",male,25.00,0,0,348122,7.650000,F G63,S
58,950,3,"Davison, Mr. Thomas Henry",male,30.00,1,0,386525,16.100000,NaN,S
59,951,1,"Chaudanson, Miss. Victorine",female,36.00,0,0,PC 17608,262.375000,B61,C
60,952,3,"Dika, Mr. Mirko",male,17.00,0,0,349232,7.895800,NaN,S
61,953,2,"McCrae, Mr. Arthur Gordon",male,32.00,0,0,237216,13.500000,NaN,S
62,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.00,0,0,347090,7.750000,NaN,S
63,955,3,"Bradley, Miss. Bridget Delia",female,22.00,0,0,334914,7.725000,NaN,Q
64,956,1,"Ryerson, Master. John Borie",male,13.00,2,2,PC 17608,262.375000,B57 B59 B63 B66,C
65,957,2,"Corey, Mrs. Percy C (Mary Phyllis Elizabeth Mi...",female,30.00,0,0,F.C.C. 13534,21.000000,NaN,S
66,958,3,"Burns, Miss. Mary Delia",female,18.00,0,0,330963,7.879200,NaN,Q
67,959,1,"Moore, Mr. Clarence Bloomfield",male,47.00,0,0,113796,42.400000,NaN,S
68,960,1,"Tucker, Mr. Gilbert Milligan Jr",male,31.00,0,0,2543,28.537500,C53,C
69,961,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.00,1,4,19950,263.000000,C23 C25 C27,S
70,962,3,"Mulvihill, Miss. Bertha E",female,24.00,0,0,382653,7.750000,NaN,Q
71,963,3,"Minkoff, Mr. Lazar",male,21.00,0,0,349211,7.895800,NaN,S
72,964,3,"Nieminen, Miss. Manta Josefina",female,29.00,0,0,3101297,7.925000,NaN,S
73,965,1,"Ovies y Rodriguez, Mr. Servando",male,28.50,0,0,PC 17562,27.720800,D43,C
74,966,1,"Geiger, Miss. Amalie",female,35.00,0,0,113503,211.500000,C130,C
75,967,1,"Keeping, Mr. Edwin",male,32.50,0,0,113503,211.500000,C132,C
76,968,3,"Miles, Mr. Frank",male,30.00,0,0,359306,8.050000,NaN,S
77,969,1,"Cornell, Mrs. Robert Clifford (Malvina Helen L...",female,55.00,2,0,11770,25.700000,C101,S
78,970,2,"Aldworth, Mr. Charles Augustus",male,30.00,0,0,248744,13.000000,NaN,S
79,971,3,"Doyle, Miss. Elizabeth",female,24.00,0,0,368702,7.750000,NaN,Q
80,972,3,"Boulos, Master. Akar",male,6.00,1,1,2678,15.245800,NaN,C
81,973,1,"Straus, Mr. Isidor",male,67.00,1,0,PC 17483,221.779200,C55 C57,S
82,974,1,"Case, Mr. Howard Brown",male,49.00,0,0,19924,26.000000,NaN,S
83,975,3,"Demetri, Mr. Marinko",male,30.00,0,0,349238,7.895800,NaN,S
84,976,2,"Lamb, Mr. John Joseph",male,30.00,0,0,240261,10.708300,NaN,Q
85,977,3,"Khalil, Mr. Betros",male,30.00,1,0,2660,14.454200,NaN,C
86,978,3,"Barry, Miss. Julia",female,27.00,0,0,330844,7.879200,NaN,Q
87,979,3,"Badman, Miss. Emily Louisa",female,18.00,0,0,A/4 31416,8.050000,NaN,S
88,980,3,"O'Donoghue, Ms. Bridget",female,30.00,0,0,364856,7.750000,NaN,Q
89,981,2,"Wells, Master. Ralph Lester",male,2.00,1,1,29103,23.000000,NaN,S
90,982,3,"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...",female,22.00,1,0,347072,13.900000,NaN,S
91,983,3,"Pedersen, Mr. Olaf",male,30.00,0,0,345498,7.775000,NaN,S
92,984,1,"Davidson, Mrs. Thornton (Orian Hays)",female,27.00,1,2,F.C. 12750,52.000000,B71,S
93,985,3,"Guest, Mr. Robert",male,30.00,0,0,376563,8.050000,NaN,S
94,986,1,"Birnbaum, Mr. Jakob",male,25.00,0,0,13905,26.000000,NaN,C
95,987,3,"Tenglin, Mr. Gunnar Isidor",male,25.00,0,0,350033,7.795800,NaN,S
96,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.00,1,0,19877,78.850000,C46,S
97,989,3,"Makinen, Mr. Kalle Edvard",male,29.00,0,0,STON/O 2. 3101268,7.925000,NaN,S
98,990,3,"Braf, Miss. Elin Ester Maria",female,20.00,0,0,347471,7.854200,NaN,S
99,991,3,"Nancarrow, Mr. William Henry",male,33.00,0,0,A./5. 3338,8.050000,NaN,S
100,992,1,"Stengel, Mrs. Charles Emil Henry (Annie May Mo...",female,43.00,1,0,11778,55.441700,C116,C
101,993,2,"Weisz, Mr. Leopold",male,27.00,1,0,228414,26.000000,NaN,S
102,994,3,"Foley, Mr. William",male,30.00,0,0,365235,7.750000,NaN,Q
103,995,3,"Johansson Palmquist, Mr. Oskar Leander",male,26.00,0,0,347070,7.775000,NaN,S
104,996,3,"Thomas, Mrs. Alexander (Thamine Thelma"")""",female,16.00,1,1,2625,8.516700,NaN,C
105,997,3,"Holthen, Mr. Johan Martin",male,28.00,0,0,C 4001,22.525000,NaN,S
106,998,3,"Buckley, Mr. Daniel",male,21.00,0,0,330920,7.820800,NaN,Q
107,999,3,"Ryan, Mr. Edward",male,30.00,0,0,383162,7.750000,NaN,Q
108,1000,3,"Willer, Mr. Aaron (Abi Weller"")""",male,30.00,0,0,3410,8.712500,NaN,S
109,1001,2,"Swane, Mr. George",male,18.50,0,0,248734,13.000000,F,S
110,1002,2,"Stanton, Mr. Samuel Ward",male,41.00,0,0,237734,15.045800,NaN,C
111,1003,3,"Shine, Miss. Ellen Natalia",female,30.00,0,0,330968,7.779200,NaN,Q
112,1004,1,"Evans, Miss. Edith Corse",female,36.00,0,0,PC 17531,31.679200,A29,C
113,1005,3,"Buckley, Miss. Katherine",female,18.50,0,0,329944,7.283300,NaN,Q
114,1006,1,"Straus, Mrs. Isidor (Rosalie Ida Blun)",female,63.00,1,0,PC 17483,221.779200,C55 C57,S
115,1007,3,"Chronopoulos, Mr. Demetrios",male,18.00,1,0,2680,14.454200,NaN,C
116,1008,3,"Thomas, Mr. John",male,30.00,0,0,2681,6.437500,NaN,C
117,1009,3,"Sandstrom, Miss. Beatrice Irene",female,1.00,1,1,PP 9549,16.700000,G6,S
118,1010,1,"Beattie, Mr. Thomson",male,36.00,0,0,13050,75.241700,C6,C
119,1011,2,"Chapman, Mrs. John Henry (Sara Elizabeth Lawry)",female,29.00,1,0,SC/AH 29037,26.000000,NaN,S
120,1012,2,"Watt, Miss. Bertha J",female,12.00,0,0,C.A. 33595,15.750000,NaN,S
121,1013,3,"Kiernan, Mr. John",male,30.00,1,0,367227,7.750000,NaN,Q
122,1014,1,"Schabert, Mrs. Paul (Emma Mock)",female,35.00,1,0,13236,57.750000,C28,C
123,1015,3,"Carver, Mr. Alfred John",male,28.00,0,0,392095,7.250000,NaN,S
124,1016,3,"Kennedy, Mr. John",male,30.00,0,0,368783,7.750000,NaN,Q
125,1017,3,"Cribb, Miss. Laura Alice",female,17.00,0,1,371362,16.100000,NaN,S
126,1018,3,"Brobeck, Mr. Karl Rudolf",male,22.00,0,0,350045,7.795800,NaN,S
127,1019,3,"McCoy, Miss. Alicia",female,30.00,2,0,367226,23.250000,NaN,Q
128,1020,2,"Bowenur, Mr. Solomon",male,42.00,0,0,211535,13.000000,NaN,S
129,1021,3,"Petersen, Mr. Marius",male,24.00,0,0,342441,8.050000,NaN,S
130,1022,3,"Spinner, Mr. Henry John",male,32.00,0,0,STON/OQ. 369943,8.050000,NaN,S
131,1023,1,"Gracie, Col. Archibald IV",male,53.00,0,0,113780,28.500000,C51,C
132,1024,3,"Lefebre, Mrs. Frank (Frances)",female,30.00,0,4,4133,25.466700,NaN,S
133,1025,3,"Thomas, Mr. Charles P",male,30.00,1,0,2621,6.437500,NaN,C
134,1026,3,"Dintcheff, Mr. Valtcho",male,43.00,0,0,349226,7.895800,NaN,S
135,1027,3,"Carlsson, Mr. Carl Robert",male,24.00,0,0,350409,7.854200,NaN,S
136,1028,3,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.225000,NaN,C
137,1029,2,"Schmidt, Mr. August",male,26.00,0,0,248659,13.000000,NaN,S
138,1030,3,"Drapkin, Miss. Jennie",female,23.00,0,0,SOTON/OQ 392083,8.050000,NaN,S
139,1031,3,"Goodwin, Mr. Charles Frederick",male,40.00,1,6,CA 2144,46.900000,NaN,S
140,1032,3,"Goodwin, Miss. Jessie Allis",female,10.00,5,2,CA 2144,46.900000,NaN,S
141,1033,1,"Daniels, Miss. Sarah",female,33.00,0,0,113781,151.550000,NaN,S
142,1034,1,"Ryerson, Mr. Arthur Larned",male,61.00,1,3,PC 17608,262.375000,B57 B59 B63 B66,C
143,1035,2,"Beauchamp, Mr. Henry James",male,28.00,0,0,244358,26.000000,NaN,S
144,1036,1,"Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lin...",male,42.00,0,0,17475,26.550000,NaN,S
145,1037,3,"Vander Planke, Mr. Julius",male,31.00,3,0,345763,18.000000,NaN,S
146,1038,1,"Hilliard, Mr. Herbert Henry",male,30.00,0,0,17463,51.862500,E46,S
147,1039,3,"Davies, Mr. Evan",male,22.00,0,0,SC/A4 23568,8.050000,NaN,S
148,1040,1,"Crafton, Mr. John Bertram",male,30.00,0,0,113791,26.550000,NaN,S
149,1041,2,"Lahtinen, Rev. William",male,30.00,1,1,250651,26.000000,NaN,S
150,1042,1,"Earnshaw, Mrs. Boulton (Olive Potter)",female,23.00,0,1,11767,83.158300,C54,C
151,1043,3,"Matinoff, Mr. Nicola",male,30.00,0,0,349255,7.895800,NaN,C
152,1044,3,"Storey, Mr. Thomas",male,60.50,0,0,3701,35.627188,NaN,S
153,1045,3,"Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)",female,36.00,0,2,350405,12.183300,NaN,S
154,1046,3,"Asplund, Master. Filip Oscar",male,13.00,4,2,347077,31.387500,NaN,S
155,1047,3,"Duquemin, Mr. Joseph",male,24.00,0,0,S.O./P.P. 752,7.550000,NaN,S
156,1048,1,"Bird, Miss. Ellen",female,29.00,0,0,PC 17483,221.779200,C97,S
157,1049,3,"Lundin, Miss. Olga Elida",female,23.00,0,0,347469,7.854200,NaN,S
158,1050,1,"Borebank, Mr. John James",male,42.00,0,0,110489,26.550000,D22,S
159,1051,3,"Peacock, Mrs. Benjamin (Edith Nile)",female,26.00,0,2,SOTON/O.Q. 3101315,13.775000,NaN,S
160,1052,3,"Smyth, Miss. Julia",female,30.00,0,0,335432,7.733300,NaN,Q
161,1053,3,"Touma, Master. Georges Youssef",male,7.00,1,1,2650,15.245800,NaN,C
162,1054,2,"Wright, Miss. Marion",female,26.00,0,0,220844,13.500000,NaN,S
163,1055,3,"Pearce, Mr. Ernest",male,30.00,0,0,343271,7.000000,NaN,S
164,1056,2,"Peruschitz, Rev. Joseph Maria",male,41.00,0,0,237393,13.000000,NaN,S
165,1057,3,"Kink-Heilmann, Mrs. Anton (Luise Heilmann)",female,26.00,1,1,315153,22.025000,NaN,S
166,1058,1,"Brandeis, Mr. Emil",male,48.00,0,0,PC 17591,50.495800,B10,C
167,1059,3,"Ford, Mr. Edward Watson",male,18.00,2,2,W./C. 6608,34.375000,NaN,S
168,1060,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,30.00,0,0,17770,27.720800,NaN,C
169,1061,3,"Hellstrom, Miss. Hilda Maria",female,22.00,0,0,7548,8.962500,NaN,S
170,1062,3,"Lithman, Mr. Simon",male,30.00,0,0,S.O./P.P. 251,7.550000,NaN,S
171,1063,3,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.225000,NaN,C
172,1064,3,"Dyker, Mr. Adolf Fredrik",male,23.00,1,0,347072,13.900000,NaN,S
173,1065,3,"Torfa, Mr. Assad",male,30.00,0,0,2673,7.229200,NaN,C
174,1066,3,"Asplund, Mr. Carl Oscar Vilhelm Gustafsson",male,40.00,1,5,347077,31.387500,NaN,S
175,1067,2,"Brown, Miss. Edith Eileen",female,15.00,0,2,29750,39.000000,NaN,S
176,1068,2,"Sincock, Miss. Maude",female,20.00,0,0,C.A. 33112,36.750000,NaN,S
177,1069,1,"Stengel, Mr. Charles Emil Henry",male,54.00,1,0,11778,55.441700,C116,C
178,1070,2,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.00,0,3,230136,39.000000,F4,S
179,1071,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.00,0,2,PC 17756,83.158300,E45,C
180,1072,2,"McCrie, Mr. James Matthew",male,30.00,0,0,233478,13.000000,NaN,S
181,1073,1,"Compton, Mr. Alexander Taylor Jr",male,37.00,1,1,PC 17756,83.158300,E52,C
182,1074,1,"Marvin, Mrs. Daniel Warner (Mary Graham Carmic...",female,18.00,1,0,113773,53.100000,D30,S
183,1075,3,"Lane, Mr. Patrick",male,30.00,0,0,7935,7.750000,NaN,Q
184,1076,1,"Douglas, Mrs. Frederick Charles (Mary Helene B...",female,27.00,1,1,PC 17558,247.520800,B58 B60,C
185,1077,2,"Maybery, Mr. Frank Hubert",male,40.00,0,0,239059,16.000000,NaN,S
186,1078,2,"Phillips, Miss. Alice Frances Louisa",female,21.00,0,1,S.O./P.P. 2,21.000000,NaN,S
187,1079,3,"Davies, Mr. Joseph",male,17.00,2,0,A/4 48873,8.050000,NaN,S
188,1080,3,"Sage, Miss. Ada",female,30.00,8,2,CA. 2343,69.550000,NaN,S
189,1081,2,"Veal, Mr. James",male,40.00,0,0,28221,13.000000,NaN,S
190,1082,2,"Angle, Mr. William A",male,34.00,1,0,226875,26.000000,NaN,S
191,1083,1,"Salomon, Mr. Abraham L",male,30.00,0,0,111163,26.000000,NaN,S
192,1084,3,"van Billiard, Master. Walter John",male,11.50,1,1,A/5. 851,14.500000,NaN,S
193,1085,2,"Lingane, Mr. John",male,61.00,0,0,235509,12.350000,NaN,Q
194,1086,2,"Drew, Master. Marshall Brines",male,8.00,0,2,28220,32.500000,NaN,S
195,1087,3,"Karlsson, Mr. Julius Konrad Eugen",male,33.00,0,0,347465,7.854200,NaN,S
196,1088,1,"Spedden, Master. Robert Douglas",male,6.00,0,2,16966,134.500000,E34,C
197,1089,3,"Nilsson, Miss. Berta Olivia",female,18.00,0,0,347066,7.775000,NaN,S
198,1090,2,"Baimbrigge, Mr. Charles Robert",male,23.00,0,0,C.A. 31030,10.500000,NaN,S
199,1091,3,"Rasmussen, Mrs. (Lena Jacobsen Solvang)",female,30.00,0,0,65305,8.112500,NaN,S
200,1092,3,"Murphy, Miss. Nora",female,30.00,0,0,36568,15.500000,NaN,Q
201,1093,3,"Danbom, Master. Gilbert Sigvard Emanuel",male,0.33,0,2,347080,14.400000,NaN,S
202,1094,1,"Astor, Col. John Jacob",male,47.00,1,0,PC 17757,227.525000,C62 C64,C
203,1095,2,"Quick, Miss. Winifred Vera",female,8.00,1,1,26360,26.000000,NaN,S
204,1096,2,"Andrew, Mr. Frank Thomas",male,25.00,0,0,C.A. 34050,10.500000,NaN,S
205,1097,1,"Omont, Mr. Alfred Fernand",male,30.00,0,0,F.C. 12998,25.741700,NaN,C
206,1098,3,"McGowan, Miss. Katherine",female,35.00,0,0,9232,7.750000,NaN,Q
207,1099,2,"Collett, Mr. Sidney C Stuart",male,24.00,0,0,28034,10.500000,NaN,S
208,1100,1,"Rosenbaum, Miss. Edith Louise",female,33.00,0,0,PC 17613,27.720800,A11,C
209,1101,3,"Delalic, Mr. Redjo",male,25.00,0,0,349250,7.895800,NaN,S
210,1102,3,"Andersen, Mr. Albert Karvin",male,32.00,0,0,C 4001,22.525000,NaN,S
211,1103,3,"Finoli, Mr. Luigi",male,30.00,0,0,SOTON/O.Q. 3101308,7.050000,NaN,S
212,1104,2,"Deacon, Mr. Percy William",male,17.00,0,0,S.O.C. 14879,73.500000,NaN,S
213,1105,2,"Howard, Mrs. Benjamin (Ellen Truelove Arman)",female,60.00,1,0,24065,26.000000,NaN,S
214,1106,3,"Andersson, Miss. Ida Augusta Margareta",female,38.00,4,2,347091,7.775000,NaN,S
215,1107,1,"Head, Mr. Christopher",male,42.00,0,0,113038,42.500000,B11,S
216,1108,3,"Mahon, Miss. Bridget Delia",female,30.00,0,0,330924,7.879200,NaN,Q
217,1109,1,"Wick, Mr. George Dennick",male,57.00,1,1,36928,164.866700,NaN,S
218,1110,1,"Widener, Mrs. George Dunton (Eleanor Elkins)",female,50.00,1,1,113503,211.500000,C80,C
219,1111,3,"Thomson, Mr. Alexander Morrison",male,30.00,0,0,32302,8.050000,NaN,S
220,1112,2,"Duran y More, Miss. Florentina",female,30.00,1,0,SC/PARIS 2148,13.858300,NaN,C
221,1113,3,"Reynolds, Mr. Harold J",male,21.00,0,0,342684,8.050000,NaN,S
222,1114,2,"Cook, Mrs. (Selena Rogers)",female,22.00,0,0,W./C. 14266,10.500000,F33,S
223,1115,3,"Karlsson, Mr. Einar Gervasius",male,21.00,0,0,350053,7.795800,NaN,S
224,1116,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.00,0,0,PC 17606,27.445800,NaN,C
225,1117,3,"Moubarek, Mrs. George (Omine Amenia"" Alexander)""",female,30.00,0,2,2661,15.245800,NaN,C
226,1118,3,"Asplund, Mr. Johan Charles",male,23.00,0,0,350054,7.795800,NaN,S
227,1119,3,"McNeill, Miss. Bridget",female,30.00,0,0,370368,7.750000,NaN,Q
228,1120,3,"Everett, Mr. Thomas James",male,40.50,0,0,C.A. 6212,15.100000,NaN,S
229,1121,2,"Hocking, Mr. Samuel James Metcalfe",male,36.00,0,0,242963,13.000000,NaN,S
230,1122,2,"Sweet, Mr. George Frederick",male,14.00,0,0,220845,65.000000,NaN,S
231,1123,1,"Willard, Miss. Constance",female,21.00,0,0,113795,26.550000,NaN,S
232,1124,3,"Wiklund, Mr. Karl Johan",male,21.00,1,0,3101266,6.495800,NaN,S
233,1125,3,"Linehan, Mr. Michael",male,30.00,0,0,330971,7.879200,NaN,Q
234,1126,1,"Cumings, Mr. John Bradley",male,39.00,1,0,PC 17599,71.283300,C85,C
235,1127,3,"Vendel, Mr. Olof Edvin",male,20.00,0,0,350416,7.854200,NaN,S
236,1128,1,"Warren, Mr. Frank Manley",male,64.00,1,0,110813,75.250000,D37,C
237,1129,3,"Baccos, Mr. Raffull",male,20.00,0,0,2679,7.225000,NaN,C
238,1130,2,"Hiltunen, Miss. Marta",female,18.00,1,1,250650,13.000000,NaN,S
239,1131,1,"Douglas, Mrs. Walter Donald (Mahala Dutton)",female,48.00,1,0,PC 17761,106.425000,C86,C
240,1132,1,"Lindstrom, Mrs. Carl Johan (Sigrid Posse)",female,55.00,0,0,112377,27.720800,NaN,C
241,1133,2,"Christy, Mrs. (Alice Frances)",female,45.00,0,2,237789,30.000000,NaN,S
242,1134,1,"Spedden, Mr. Frederic Oakley",male,45.00,1,1,16966,134.500000,E34,C
243,1135,3,"Hyman, Mr. Abraham",male,30.00,0,0,3470,7.887500,NaN,S
244,1136,3,"Johnston, Master. William Arthur Willie""""",male,30.00,1,2,W./C. 6607,23.450000,NaN,S
245,1137,1,"Kenyon, Mr. Frederick R",male,41.00,1,0,17464,51.862500,D21,S
246,1138,2,"Karnes, Mrs. J Frank (Claire Bennett)",female,22.00,0,0,F.C.C. 13534,21.000000,NaN,S
247,1139,2,"Drew, Mr. James Vivian",male,42.00,1,1,28220,32.500000,NaN,S
248,1140,2,"Hold, Mrs. Stephen (Annie Margaret Hill)",female,29.00,1,0,26707,26.000000,NaN,S

In [30]:
test = dummies(test, ['Embarked'])
test['Sex'] = df['Sex'] == 'male'

In [31]:
# predict the test set in test.csv
bins = df['Fare'].quantile([0, 0.25, 0.75, 1])
bin_feat = []
print(bins.iloc[3])
for i in test['Fare']:
    if i <=bins.iloc[1]:
        bin_feat.append(1)
    elif i >bins.iloc[1] and i <=bins.iloc[2]:
        bin_feat.append(2)
    elif i > bins.iloc[2]:
        bin_feat.append(3)
test['Fare_bin'] = bin_feat

512.3292

In [32]:
bin_feat = []
for i in test['Age']:
    if i<=1:
        bin_feat.append(1)
    elif i >1 and i <=5:
        bin_feat.append(2)
    elif i > 5 and i<=12:
        bin_feat.append(3)
    elif i > 12 and i <=18:
        bin_feat.append(4)
    elif i > 18 and i<=30:
        bin_feat.append(5)
    elif i > 30 and i <= 45:
        bin_feat.append(6)
    elif i > 45 and i <=60:
        bin_feat.append(7)
    elif i > 60:
        bin_feat.append(8)

test['Age_bin'] = bin_feat

In [33]:
# drop columns
test.drop('Name', axis=1, inplace=True)
test.drop('Ticket', axis=1, inplace=True)
#df.drop('Embarked', axis=1, inplace=True)
test.drop('PassengerId', axis=1, inplace=True)
test.drop('Cabin', axis=1, inplace=True)

In [34]:
test

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Fare_bin,Age_bin
0,3,False,34.50,0,0,7.829200,0,1,0,1,6
1,3,False,47.00,1,0,7.000000,0,0,1,1,7
2,2,False,62.00,0,0,9.687500,0,1,0,2,8
3,3,False,27.00,0,0,8.662500,0,0,1,2,5
4,3,False,22.00,1,1,12.287500,0,0,1,2,5
5,3,False,14.00,0,0,9.225000,0,0,1,2,4
6,3,False,30.00,0,0,7.629200,0,1,0,1,5
7,2,False,26.00,1,1,29.000000,0,0,1,2,5
8,3,False,18.00,0,0,7.229200,1,0,0,1,4
9,3,False,21.00,2,0,24.150000,0,0,1,2,5
10,3,False,30.00,0,0,7.895800,0,0,1,1,5
11,1,False,46.00,0,0,26.000000,0,0,1,2,7
12,1,False,23.00,1,0,82.266700,0,0,1,3,5
13,2,False,63.00,1,0,26.000000,0,0,1,2,8
14,1,False,47.00,1,0,61.175000,0,0,1,3,7
15,2,False,24.00,1,0,27.720800,1,0,0,2,5
16,2,False,35.00,0,0,12.350000,0,1,0,2,6
17,3,False,21.00,0,0,7.225000,1,0,0,1,5
18,3,False,27.00,1,0,7.925000,0,0,1,2,5
19,3,False,45.00,0,0,7.225000,1,0,0,1,6
20,1,False,55.00,1,0,59.400000,1,0,0,3,7
21,3,False,9.00,0,1,3.170800,0,0,1,1,3
22,1,False,30.00,0,0,31.683300,0,0,1,3,5
23,1,False,21.00,0,1,61.379200,1,0,0,3,5
24,1,False,48.00,1,3,262.375000,1,0,0,3,7
25,3,False,50.00,1,0,14.500000,0,0,1,2,7
26,1,False,22.00,0,1,61.979200,1,0,0,3,5
27,3,False,22.50,0,0,7.225000,1,0,0,1,5
28,1,False,41.00,0,0,30.500000,0,0,1,2,6
29,3,False,30.00,2,0,21.679200,1,0,0,2,5
30,2,False,50.00,1,0,26.000000,0,0,1,2,7
31,2,False,24.00,2,0,31.500000,0,0,1,3,5
32,3,False,33.00,1,2,20.575000,0,0,1,2,6
33,3,False,30.00,1,2,23.450000,0,0,1,2,5
34,1,False,30.00,1,0,57.750000,1,0,0,3,5
35,3,False,18.50,0,0,7.229200,1,0,0,1,5
36,3,False,30.00,0,0,8.050000,0,0,1,2,5
37,3,False,21.00,0,0,8.662500,0,0,1,2,5
38,3,False,25.00,0,0,9.500000,0,0,1,2,5
39,3,False,30.00,0,0,56.495800,0,0,1,3,5
40,3,False,39.00,0,1,13.416700,1,0,0,2,6
41,1,False,30.00,0,0,26.550000,0,0,1,2,5
42,3,False,41.00,0,0,7.850000,0,0,1,1,6
43,2,False,30.00,0,0,13.000000,0,0,1,2,5
44,1,False,45.00,1,0,52.554200,0,0,1,3,6
45,3,False,25.00,0,0,7.925000,0,0,1,2,5
46,1,False,45.00,0,0,29.700000,1,0,0,2,6
47,3,False,30.00,0,0,7.750000,0,1,0,1,5
48,1,False,60.00,0,0,76.291700,1,0,0,3,7
49,3,False,36.00,0,2,15.900000,0,0,1,2,6
50,1,False,24.00,1,0,60.000000,0,0,1,3,5
51,2,False,27.00,0,0,15.033300,1,0,0,2,5
52,2,False,20.00,2,1,23.000000,0,0,1,2,5
53,1,False,28.00,3,2,263.000000,0,0,1,3,5
54,2,False,30.00,0,0,15.579200,1,0,0,2,5
55,3,False,10.00,4,1,29.125000,0,1,0,2,3
56,3,False,35.00,0,0,7.895800,0,0,1,1,6
57,3,False,25.00,0,0,7.650000,0,0,1,1,5
58,3,False,30.00,1,0,16.100000,0,0,1,2,5
59,1,False,36.00,0,0,262.375000,1,0,0,3,6
60,3,False,17.00,0,0,7.895800,0,0,1,1,4
61,2,False,32.00,0,0,13.500000,0,0,1,2,6
62,3,False,18.00,0,0,7.750000,0,0,1,1,4
63,3,False,22.00,0,0,7.725000,0,1,0,1,5
64,1,False,13.00,2,2,262.375000,1,0,0,3,4
65,2,False,30.00,0,0,21.000000,0,0,1,2,5
66,3,False,18.00,0,0,7.879200,0,1,0,1,4
67,1,False,47.00,0,0,42.400000,0,0,1,3,7
68,1,False,31.00,0,0,28.537500,1,0,0,2,6
69,1,False,60.00,1,4,263.000000,0,0,1,3,7
70,3,False,24.00,0,0,7.750000,0,1,0,1,5
71,3,False,21.00,0,0,7.895800,0,0,1,1,5
72,3,False,29.00,0,0,7.925000,0,0,1,2,5
73,1,False,28.50,0,0,27.720800,1,0,0,2,5
74,1,False,35.00,0,0,211.500000,1,0,0,3,6
75,1,False,32.50,0,0,211.500000,1,0,0,3,6
76,3,False,30.00,0,0,8.050000,0,0,1,2,5
77,1,False,55.00,2,0,25.700000,0,0,1,2,7
78,2,False,30.00,0,0,13.000000,0,0,1,2,5
79,3,False,24.00,0,0,7.750000,0,1,0,1,5
80,3,False,6.00,1,1,15.245800,1,0,0,2,3
81,1,False,67.00,1,0,221.779200,0,0,1,3,8
82,1,False,49.00,0,0,26.000000,0,0,1,2,7
83,3,False,30.00,0,0,7.895800,0,0,1,1,5
84,2,False,30.00,0,0,10.708300,0,1,0,2,5
85,3,False,30.00,1,0,14.454200,1,0,0,2,5
86,3,False,27.00,0,0,7.879200,0,1,0,1,5
87,3,False,18.00,0,0,8.050000,0,0,1,2,4
88,3,False,30.00,0,0,7.750000,0,1,0,1,5
89,2,False,2.00,1,1,23.000000,0,0,1,2,2
90,3,False,22.00,1,0,13.900000,0,0,1,2,5
91,3,False,30.00,0,0,7.775000,0,0,1,1,5
92,1,False,27.00,1,2,52.000000,0,0,1,3,5
93,3,False,30.00,0,0,8.050000,0,0,1,2,5
94,1,False,25.00,0,0,26.000000,1,0,0,2,5
95,3,False,25.00,0,0,7.795800,0,0,1,1,5
96,1,False,76.00,1,0,78.850000,0,0,1,3,8
97,3,False,29.00,0,0,7.925000,0,0,1,2,5
98,3,False,20.00,0,0,7.854200,0,0,1,1,5
99,3,False,33.00,0,0,8.050000,0,0,1,2,6
100,1,False,43.00,1,0,55.441700,1,0,0,3,6
101,2,False,27.00,1,0,26.000000,0,0,1,2,5
102,3,False,30.00,0,0,7.750000,0,1,0,1,5
103,3,False,26.00,0,0,7.775000,0,0,1,1,5
104,3,False,16.00,1,1,8.516700,1,0,0,2,4
105,3,False,28.00,0,0,22.525000,0,0,1,2,5
106,3,False,21.00,0,0,7.820800,0,1,0,1,5
107,3,False,30.00,0,0,7.750000,0,1,0,1,5
108,3,False,30.00,0,0,8.712500,0,0,1,2,5
109,2,False,18.50,0,0,13.000000,0,0,1,2,5
110,2,False,41.00,0,0,15.045800,1,0,0,2,6
111,3,False,30.00,0,0,7.779200,0,1,0,1,5
112,1,False,36.00,0,0,31.679200,1,0,0,3,6
113,3,False,18.50,0,0,7.283300,0,1,0,1,5
114,1,False,63.00,1,0,221.779200,0,0,1,3,8
115,3,False,18.00,1,0,14.454200,1,0,0,2,4
116,3,False,30.00,0,0,6.437500,1,0,0,1,5
117,3,False,1.00,1,1,16.700000,0,0,1,2,1
118,1,False,36.00,0,0,75.241700,1,0,0,3,6
119,2,False,29.00,1,0,26.000000,0,0,1,2,5
120,2,False,12.00,0,0,15.750000,0,0,1,2,3
121,3,False,30.00,1,0,7.750000,0,1,0,1,5
122,1,False,35.00,1,0,57.750000,1,0,0,3,6
123,3,False,28.00,0,0,7.250000,0,0,1,1,5
124,3,False,30.00,0,0,7.750000,0,1,0,1,5
125,3,False,17.00,0,1,16.100000,0,0,1,2,4
126,3,False,22.00,0,0,7.795800,0,0,1,1,5
127,3,False,30.00,2,0,23.250000,0,1,0,2,5
128,2,False,42.00,0,0,13.000000,0,0,1,2,6
129,3,False,24.00,0,0,8.050000,0,0,1,2,5
130,3,False,32.00,0,0,8.050000,0,0,1,2,6
131,1,False,53.00,0,0,28.500000,1,0,0,2,7
132,3,False,30.00,0,4,25.466700,0,0,1,2,5
133,3,False,30.00,1,0,6.437500,1,0,0,1,5
134,3,False,43.00,0,0,7.895800,0,0,1,1,6
135,3,False,24.00,0,0,7.854200,0,0,1,1,5
136,3,False,26.50,0,0,7.225000,1,0,0,1,5
137,2,False,26.00,0,0,13.000000,0,0,1,2,5
138,3,False,23.00,0,0,8.050000,0,0,1,2,5
139,3,False,40.00,1,6,46.900000,0,0,1,3,6
140,3,False,10.00,5,2,46.900000,0,0,1,3,3
141,1,False,33.00,0,0,151.550000,0,0,1,3,6
142,1,False,61.00,1,3,262.375000,1,0,0,3,8
143,2,False,28.00,0,0,26.000000,0,0,1,2,5
144,1,False,42.00,0,0,26.550000,0,0,1,2,6
145,3,False,31.00,3,0,18.000000,0,0,1,2,6
146,1,False,30.00,0,0,51.862500,0,0,1,3,5
147,3,False,22.00,0,0,8.050000,0,0,1,2,5
148,1,False,30.00,0,0,26.550000,0,0,1,2,5
149,2,False,30.00,1,1,26.000000,0,0,1,2,5
150,1,False,23.00,0,1,83.158300,1,0,0,3,5
151,3,False,30.00,0,0,7.895800,1,0,0,1,5
152,3,False,60.50,0,0,35.627188,0,0,1,3,8
153,3,False,36.00,0,2,12.183300,0,0,1,2,6
154,3,False,13.00,4,2,31.387500,0,0,1,3,4
155,3,False,24.00,0,0,7.550000,0,0,1,1,5
156,1,False,29.00,0,0,221.779200,0,0,1,3,5
157,3,False,23.00,0,0,7.854200,0,0,1,1,5
158,1,False,42.00,0,0,26.550000,0,0,1,2,6
159,3,False,26.00,0,2,13.775000,0,0,1,2,5
160,3,False,30.00,0,0,7.733300,0,1,0,1,5
161,3,False,7.00,1,1,15.245800,1,0,0,2,3
162,2,False,26.00,0,0,13.500000,0,0,1,2,5
163,3,False,30.00,0,0,7.000000,0,0,1,1,5
164,2,False,41.00,0,0,13.000000,0,0,1,2,6
165,3,False,26.00,1,1,22.025000,0,0,1,2,5
166,1,False,48.00,0,0,50.495800,1,0,0,3,7
167,3,False,18.00,2,2,34.375000,0,0,1,3,4
168,1,False,30.00,0,0,27.720800,1,0,0,2,5
169,3,False,22.00,0,0,8.962500,0,0,1,2,5
170,3,False,30.00,0,0,7.550000,0,0,1,1,5
171,3,False,27.00,0,0,7.225000,1,0,0,1,5
172,3,False,23.00,1,0,13.900000,0,0,1,2,5
173,3,False,30.00,0,0,7.229200,1,0,0,1,5
174,3,False,40.00,1,5,31.387500,0,0,1,3,6
175,2,False,15.00,0,2,39.000000,0,0,1,3,4
176,2,False,20.00,0,0,36.750000,0,0,1,3,5
177,1,False,54.00,1,0,55.441700,1,0,0,3,7
178,2,False,36.00,0,3,39.000000,0,0,1,3,6
179,1,False,64.00,0,2,83.158300,1,0,0,3,8
180,2,False,30.00,0,0,13.000000,0,0,1,2,5
181,1,False,37.00,1,1,83.158300,1,0,0,3,6
182,1,False,18.00,1,0,53.100000,0,0,1,3,4
183,3,False,30.00,0,0,7.750000,0,1,0,1,5
184,1,False,27.00,1,1,247.520800,1,0,0,3,5
185,2,False,40.00,0,0,16.000000,0,0,1,2,6
186,2,False,21.00,0,1,21.000000,0,0,1,2,5
187,3,False,17.00,2,0,8.050000,0,0,1,2,4
188,3,False,30.00,8,2,69.550000,0,0,1,3,5
189,2,False,40.00,0,0,13.000000,0,0,1,2,6
190,2,False,34.00,1,0,26.000000,0,0,1,2,6
191,1,False,30.00,0,0,26.000000,0,0,1,2,5
192,3,False,11.50,1,1,14.500000,0,0,1,2,3
193,2,False,61.00,0,0,12.350000,0,1,0,2,8
194,2,False,8.00,0,2,32.500000,0,0,1,3,3
195,3,False,33.00,0,0,7.854200,0,0,1,1,6
196,1,False,6.00,0,2,134.500000,1,0,0,3,3
197,3,False,18.00,0,0,7.775000,0,0,1,1,4
198,2,False,23.00,0,0,10.500000,0,0,1,2,5
199,3,False,30.00,0,0,8.112500,0,0,1,2,5
200,3,False,30.00,0,0,15.500000,0,1,0,2,5
201,3,False,0.33,0,2,14.400000,0,0,1,2,1
202,1,False,47.00,1,0,227.525000,1,0,0,3,7
203,2,False,8.00,1,1,26.000000,0,0,1,2,3
204,2,False,25.00,0,0,10.500000,0,0,1,2,5
205,1,False,30.00,0,0,25.741700,1,0,0,2,5
206,3,False,35.00,0,0,7.750000,0,1,0,1,6
207,2,False,24.00,0,0,10.500000,0,0,1,2,5
208,1,False,33.00,0,0,27.720800,1,0,0,2,6
209,3,False,25.00,0,0,7.895800,0,0,1,1,5
210,3,False,32.00,0,0,22.525000,0,0,1,2,6
211,3,False,30.00,0,0,7.050000,0,0,1,1,5
212,2,False,17.00,0,0,73.500000,0,0,1,3,4
213,2,False,60.00,1,0,26.000000,0,0,1,2,7
214,3,False,38.00,4,2,7.775000,0,0,1,1,6
215,1,False,42.00,0,0,42.500000,0,0,1,3,6
216,3,False,30.00,0,0,7.879200,0,1,0,1,5
217,1,False,57.00,1,1,164.866700,0,0,1,3,7
218,1,False,50.00,1,1,211.500000,1,0,0,3,7
219,3,False,30.00,0,0,8.050000,0,0,1,2,5
220,2,False,30.00,1,0,13.858300,1,0,0,2,5
221,3,False,21.00,0,0,8.050000,0,0,1,2,5
222,2,False,22.00,0,0,10.500000,0,0,1,2,5
223,3,False,21.00,0,0,7.795800,0,0,1,1,5
224,1,False,53.00,0,0,27.445800,1,0,0,2,7
225,3,False,30.00,0,2,15.245800,1,0,0,2,5
226,3,False,23.00,0,0,7.795800,0,0,1,1,5
227,3,False,30.00,0,0,7.750000,0,1,0,1,5
228,3,False,40.50,0,0,15.100000,0,0,1,2,6
229,2,False,36.00,0,0,13.000000,0,0,1,2,6
230,2,False,14.00,0,0,65.000000,0,0,1,3,4
231,1,False,21.00,0,0,26.550000,0,0,1,2,5
232,3,False,21.00,1,0,6.495800,0,0,1,1,5
233,3,False,30.00,0,0,7.879200,0,1,0,1,5
234,1,False,39.00,1,0,71.283300,1,0,0,3,6
235,3,False,20.00,0,0,7.854200,0,0,1,1,5
236,1,False,64.00,1,0,75.250000,1,0,0,3,8
237,3,False,20.00,0,0,7.225000,1,0,0,1,5
238,2,False,18.00,1,1,13.000000,0,0,1,2,4
239,1,False,48.00,1,0,106.425000,1,0,0,3,7
240,1,False,55.00,0,0,27.720800,1,0,0,2,7
241,2,False,45.00,0,2,30.000000,0,0,1,2,6
242,1,False,45.00,1,1,134.500000,1,0,0,3,6
243,3,False,30.00,0,0,7.887500,0,0,1,1,5
244,3,False,30.00,1,2,23.450000,0,0,1,2,5
245,1,False,41.00,1,0,51.862500,0,0,1,3,6
246,2,False,22.00,0,0,21.000000,0,0,1,2,5
247,2,False,42.00,1,1,32.500000,0,0,1,3,6
248,2,False,29.00,1,0,26.000000,0,0,1,2,5
249,3,False,30.00,1,0,14.454200,1,0,0,2,5
250,2,False,0.92,1,2,27.750000,0,0,1,2,1
251,3,False,20.00,0,0,7.925000,0,0,1,2,5
252,1,False,27.00,1,0,136.779200,1,0,0,3,5
253,3,False,24.00,0,0,9.325000,0,0,1,2,5
254,3,False,32.50,0,0,9.500000,0,0,1,2,6
255,3,False,30.00,0,0,7.550000,0,0,1,1,5
256,3,False,30.00,0,0,7.750000,0,1,0,1,5
257,3,False,28.00,0,0,8.050000,0,0,1,2,5
258,2,False,19.00,0,0,13.000000,0,0,1,2,5
259,3,False,21.00,0,0,7.775000,0,0,1,1,5
260,3,False,36.50,1,0,17.400000,0,0,1,2,6
261,3,False,21.00,0,0,7.854200,0,0,1,1,5
262,2,False,29.00,0,2,23.000000,0,0,1,2,5
263,3,False,1.00,1,1,12.183300,0,0,1,2,1
264,2,False,30.00,0,0,12.737500,1,0,0,2,5
265,3,False,30.00,0,0,7.895800,0,0,1,1,5
266,1,False,30.00,0,0,0.000000,0,0,1,1,5
267,3,False,30.00,0,0,7.550000,0,0,1,1,5
268,3,False,30.00,0,0,8.050000,0,0,1,2,5
269,3,False,17.00,0,0,8.662500,0,0,1,2,4
270,1,False,46.00,0,0,75.241700,1,0,0,3,7
271,3,False,30.00,0,0,7.750000,0,1,0,1,5
272,1,False,26.00,1,0,136.779200,1,0,0,3,5
273,3,False,30.00,1,0,15.500000,0,1,0,2,5
274,3,False,30.00,0,0,7.225000,1,0,0,1,5
275,2,False,20.00,1,0,26.000000,0,0,1,2,5
276,2,False,28.00,0,0,10.500000,0,0,1,2,5
277,2,False,40.00,1,0,26.000000,0,0,1,2,6
278,2,False,30.00,1,0,21.000000,0,0,1,2,5
279,2,False,22.00,0,0,10.500000,0,0,1,2,5
280,3,False,23.00,0,0,8.662500,0,0,1,2,5
281,3,False,0.75,1,1,13.775000,0,0,1,2,1
282,3,False,30.00,0,0,7.750000,0,1,0,1,5
283,3,False,9.00,1,1,15.245800,1,0,0,2,3
284,3,False,2.00,1,1,20.212500,0,0,1,2,2
285,3,False,36.00,0,0,7.250000,0,0,1,1,6
286,3,False,30.00,0,0,7.250000,0,0,1,1,5
287,1,False,24.00,1,0,82.266700,0,0,1,3,5
288,3,False,30.00,0,0,7.229200,1,0,0,1,5
289,3,False,30.00,0,0,8.050000,0,0,1,2,5
290,1,False,30.00,0,0,39.600000,0,0,1,3,5
291,3,False,30.00,0,0,6.950000,0,1,0,1,5
292,3,False,30.00,0,0,7.229200,1,0,0,1,5
293,1,False,53.00,1,1,81.858300,0,0,1,3,7
294,3,False,36.00,0,0,9.500000,0,0,1,2,6
295,3,False,26.00,0,0,7.895800,0,0,1,1,5
296,2,False,1.00,1,2,41.579200,1,0,0,3,1
297,3,False,30.00,2,0,21.679200,1,0,0,2,5
298,1,False,30.00,0,0,45.500000,0,0,1,3,5
299,3,False,29.00,0,0,7.854200,0,0,1,1,5
300,3,False,32.00,0,0,7.775000,0,0,1,1,6
301,2,False,30.00,0,0,15.045800,1,0,0,2,5
302,2,False,43.00,0,1,21.000000,0,0,1,2,6
303,3,False,24.00,0,0,8.662500,0,0,1,2,5
304,3,False,30.00,0,0,7.750000,0,1,0,1,5
305,1,False,64.00,1,1,26.550000,0,0,1,2,8
306,1,False,30.00,1,2,151.550000,0,0,1,3,5
307,3,False,0.83,0,1,9.350000,0,0,1,2,1
308,1,False,55.00,1,1,93.500000,0,0,1,3,7
309,3,False,45.00,1,0,14.108300,0,0,1,2,6
310,3,False,18.00,0,0,8.662500,0,0,1,2,4
311,3,False,22.00,0,0,7.225000,1,0,0,1,5
312,3,False,30.00,0,0,7.575000,0,0,1,1,5
313,3,False,37.00,0,0,7.750000,0,1,0,1,6
314,1,False,55.00,0,0,135.633300,1,0,0,3,7
315,3,False,17.00,0,0,7.733300,0,1,0,1,4
316,1,False,57.00,1,0,146.520800,1,0,0,3,7
317,2,False,19.00,0,0,10.500000,0,0,1,2,5
318,3,False,27.00,0,0,7.854200,0,0,1,1,5
319,2,False,22.00,2,0,31.500000,0,0,1,3,5
320,3,False,26.00,0,0,7.775000,0,0,1,1,5
321,3,False,25.00,0,0,7.229200,1,0,0,1,5
322,2,False,26.00,0,0,13.000000,0,0,1,2,5
323,1,False,33.00,0,0,26.550000,0,0,1,2,6
324,1,False,39.00,0,0,211.337500,0,0,1,3,6
325,3,False,23.00,0,0,7.050000,0,0,1,1,5
326,2,False,12.00,2,1,39.000000,0,0,1,3,3
327,1,False,46.00,0,0,79.200000,1,0,0,3,7
328,2,False,29.00,1,0,26.000000,0,0,1,2,5
329,2,False,21.00,0,0,13.000000,0,0,1,2,5
330,2,False,48.00,0,2,36.750000,0,0,1,3,7
331,1,False,39.00,0,0,29.700000,1,0,0,2,6
332,3,False,30.00,0,0,7.225000,1,0,0,1,5
333,3,False,19.00,1,1,15.741700,1,0,0,2,5
334,3,False,27.00,0,0,7.895800,0,0,1,1,5
335,1,False,30.00,0,0,26.000000,0,0,1,2,5
336,2,False,32.00,0,0,13.000000,0,0,1,2,6
337,3,False,39.00,0,2,7.229200,1,0,0,1,6
338,2,False,25.00,0,0,31.500000,0,0,1,3,5
339,3,False,30.00,0,0,7.229200,1,0,0,1,5
340,2,False,18.00,0,0,10.500000,0,0,1,2,4
341,3,False,32.00,0,0,7.579200,0,0,1,1,6
342,3,False,30.00,1,9,69.550000,0,0,1,3,5
343,1,False,58.00,0,1,512.329200,1,0,0,3,7
344,3,False,30.00,1,1,14.500000,0,0,1,2,5
345,3,False,16.00,0,0,7.650000,0,0,1,1,4
346,2,False,26.00,0,0,13.000000,0,0,1,2,5
347,3,False,38.00,0,0,7.229200,1,0,0,1,6
348,2,False,24.00,0,0,13.500000,0,0,1,2,5
349,2,False,31.00,0,0,21.000000,0,0,1,2,6
350,1,False,45.00,0,1,63.358300,1,0,0,3,6
351,2,False,25.00,0,0,10.500000,0,0,1,2,5
352,2,False,18.00,0,0,73.500000,0,0,1,3,4
353,2,False,49.00,1,2,65.000000,0,0,1,3,7
354,3,False,0.17,1,2,20.575000,0,0,1,2,1
355,1,False,50.00,0,0,26.000000,0,0,1,2,7
356,1,False,59.00,2,0,51.479200,0,0,1,3,7
357,3,False,30.00,0,0,7.879200,0,0,1,1,5
358,3,False,30.00,0,0,7.750000,0,1,0,1,5
359,3,False,30.00,1,0,15.550000,0,0,1,2,5
360,3,False,14.50,8,2,69.550000,0,0,1,3,4
361,2,False,24.00,1,1,37.004200,1,0,0,3,5
362,2,False,31.00,0,0,21.000000,0,0,1,2,6
363,3,False,27.00,0,0,8.662500,0,0,1,2,5
364,1,False,25.00,1,0,55.441700,1,0,0,3,5
365,3,False,30.00,1,9,69.550000,0,0,1,3,5
366,3,False,30.00,1,0,14.458300,1,0,0,2,5
367,3,False,22.00,0,0,39.687500,0,0,1,3,5
368,1,False,45.00,0,1,59.400000,1,0,0,3,6
369,2,False,29.00,0,0,13.858300,1,0,0,2,5
370,2,False,21.00,1,0,11.500000,0,0,1,2,5
371,1,False,31.00,0,0,134.500000,1,0,0,3,6
372,1,False,49.00,0,0,0.000000,0,0,1,1,7
373,2,False,44.00,0,0,13.000000,0,0,1,2,6
374,1,False,54.00,1,1,81.858300,0,0,1,3,7
375,1,False,45.00,0,0,262.375000,1,0,0,3,6
376,3,False,22.00,2,0,8.662500,0,0,1,2,5
377,2,False,21.00,0,0,11.500000,0,0,1,2,5
378,1,False,55.00,0,0,50.000000,0,0,1,3,7
379,3,False,5.00,4,2,31.387500,0,0,1,3,2
380,3,False,30.00,0,0,7.750000,0,1,0,1,5
381,3,False,26.00,0,0,7.879200,0,1,0,1,5
382,3,False,30.00,0,0,14.500000,0,0,1,2,5
383,3,False,19.00,1,0,16.100000,0,0,1,2,5
384,2,False,30.00,0,0,12.875000,0,0,1,2,5
385,2,False,24.00,1,2,65.000000,0,0,1,3,5
386,3,False,24.00,0,0,7.775000,0,0,1,1,5
387,2,False,57.00,0,0,13.000000,0,0,1,2,7
388,3,False,21.00,0,0,7.750000,0,1,0,1,5
389,3,False,6.00,3,1,21.075000,0,0,1,2,3
390,1,False,23.00,0,0,93.500000,0,0,1,3,5
391,1,False,51.00,0,1,39.400000,0,0,1,3,7
392,3,False,13.00,0,2,20.250000,0,0,1,2,4
393,2,False,47.00,0,0,10.500000,0,0,1,2,7
394,3,False,29.00,3,1,22.025000,0,0,1,2,5
395,1,False,18.00,1,0,60.000000,0,0,1,3,4
396,3,False,24.00,0,0,7.250000,0,1,0,1,5
397,1,False,48.00,1,1,79.200000,1,0,0,3,7
398,3,False,22.00,0,0,7.775000,0,0,1,1,5
399,3,False,31.00,0,0,7.733300,0,1,0,1,6
400,1,False,30.00,0,0,164.866700,0,0,1,3,5
401,2,False,38.00,1,0,21.000000,0,0,1,2,6
402,1,False,22.00,0,1,59.400000,1,0,0,3,5
403,1,False,17.00,0,0,47.100000,0,0,1,3,4
404,1,False,43.00,1,0,27.720800,1,0,0,2,6
405,2,False,20.00,0,0,13.862500,1,0,0,2,5
406,2,False,23.00,1,0,10.500000,0,0,1,2,5
407,1,False,50.00,1,1,211.500000,1,0,0,3,7
408,3,False,30.00,0,0,7.720800,0,1,0,1,5
409,3,False,3.00,1,1,13.775000,0,0,1,2,2
410,3,False,30.00,0,0,7.750000,0,1,0,1,5
411,1,False,37.00,1,0,90.000000,0,1,0,3,6
412,3,False,28.00,0,0,7.775000,0,0,1,1,5
413,3,False,30.00,0,0,8.050000,0,0,1,2,5
414,1,False,39.00,0,0,108.900000,1,0,0,3,6
415,3,False,38.50,0,0,7.250000,0,0,1,1,6
416,3,False,30.00,0,0,8.050000,0,0,1,2,5
417,3,False,30.00,1,1,22.358300,1,0,0,2,5

In [35]:
x_train

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Fare_bin,Age_bin
0,3,True,22.00,1,0,7.2500,0,0,1,1,5
1,1,False,38.00,1,0,71.2833,1,0,0,3,6
2,3,False,26.00,0,0,7.9250,0,0,1,2,5
3,1,False,35.00,1,0,53.1000,0,0,1,3,6
4,3,True,35.00,0,0,8.0500,0,0,1,2,6
5,3,True,30.00,0,0,8.4583,0,1,0,2,5
6,1,True,54.00,0,0,51.8625,0,0,1,3,7
7,3,True,2.00,3,1,21.0750,0,0,1,2,2
8,3,False,27.00,0,2,11.1333,0,0,1,2,5
9,2,False,14.00,1,0,30.0708,1,0,0,2,4
10,3,False,4.00,1,1,16.7000,0,0,1,2,2
11,1,False,58.00,0,0,26.5500,0,0,1,2,7
12,3,True,20.00,0,0,8.0500,0,0,1,2,5
13,3,True,39.00,1,5,31.2750,0,0,1,3,6
14,3,False,14.00,0,0,7.8542,0,0,1,1,4
15,2,False,55.00,0,0,16.0000,0,0,1,2,7
16,3,True,2.00,4,1,29.1250,0,1,0,2,2
17,2,True,30.00,0,0,13.0000,0,0,1,2,5
18,3,False,31.00,1,0,18.0000,0,0,1,2,6
19,3,False,30.00,0,0,7.2250,1,0,0,1,5
20,2,True,35.00,0,0,26.0000,0,0,1,2,6
21,2,True,34.00,0,0,13.0000,0,0,1,2,6
22,3,False,15.00,0,0,8.0292,0,1,0,2,4
23,1,True,28.00,0,0,35.5000,0,0,1,3,5
24,3,False,8.00,3,1,21.0750,0,0,1,2,3
25,3,False,38.00,1,5,31.3875,0,0,1,3,6
26,3,True,30.00,0,0,7.2250,1,0,0,1,5
27,1,True,19.00,3,2,263.0000,0,0,1,3,5
28,3,False,30.00,0,0,7.8792,0,1,0,1,5
29,3,True,30.00,0,0,7.8958,0,0,1,1,5
30,1,True,40.00,0,0,27.7208,1,0,0,2,6
31,1,False,30.00,1,0,146.5208,1,0,0,3,5
32,3,False,30.00,0,0,7.7500,0,1,0,1,5
33,2,True,66.00,0,0,10.5000,0,0,1,2,8
34,1,True,28.00,1,0,82.1708,1,0,0,3,5
35,1,True,42.00,1,0,52.0000,0,0,1,3,6
36,3,True,30.00,0,0,7.2292,1,0,0,1,5
37,3,True,21.00,0,0,8.0500,0,0,1,2,5
38,3,False,18.00,2,0,18.0000,0,0,1,2,4
39,3,False,14.00,1,0,11.2417,1,0,0,2,4
40,3,False,40.00,1,0,9.4750,0,0,1,2,6
41,2,False,27.00,1,0,21.0000,0,0,1,2,5
42,3,True,30.00,0,0,7.8958,1,0,0,1,5
43,2,False,3.00,1,2,41.5792,1,0,0,3,2
44,3,False,19.00,0,0,7.8792,0,1,0,1,5
45,3,True,30.00,0,0,8.0500,0,0,1,2,5
46,3,True,30.00,1,0,15.5000,0,1,0,2,5
47,3,False,30.00,0,0,7.7500,0,1,0,1,5
48,3,True,30.00,2,0,21.6792,1,0,0,2,5
49,3,False,18.00,1,0,17.8000,0,0,1,2,4
50,3,True,7.00,4,1,39.6875,0,0,1,3,3
51,3,True,21.00,0,0,7.8000,0,0,1,1,5
52,1,False,49.00,1,0,76.7292,1,0,0,3,7
53,2,False,29.00,1,0,26.0000,0,0,1,2,5
54,1,True,65.00,0,1,61.9792,1,0,0,3,8
55,1,True,30.00,0,0,35.5000,0,0,1,3,5
56,2,False,21.00,0,0,10.5000,0,0,1,2,5
57,3,True,28.50,0,0,7.2292,1,0,0,1,5
58,2,False,5.00,1,2,27.7500,0,0,1,2,2
59,3,True,11.00,5,2,46.9000,0,0,1,3,3
60,3,True,22.00,0,0,7.2292,1,0,0,1,5
61,1,False,38.00,0,0,80.0000,0,0,0,3,6
62,1,True,45.00,1,0,83.4750,0,0,1,3,6
63,3,True,4.00,3,2,27.9000,0,0,1,2,2
64,1,True,30.00,0,0,27.7208,1,0,0,2,5
65,3,True,30.00,1,1,15.2458,1,0,0,2,5
66,2,False,29.00,0,0,10.5000,0,0,1,2,5
67,3,True,19.00,0,0,8.1583,0,0,1,2,5
68,3,False,17.00,4,2,7.9250,0,0,1,2,4
69,3,True,26.00,2,0,8.6625,0,0,1,2,5
70,2,True,32.00,0,0,10.5000,0,0,1,2,6
71,3,False,16.00,5,2,46.9000,0,0,1,3,4
72,2,True,21.00,0,0,73.5000,0,0,1,3,5
73,3,True,26.00,1,0,14.4542,1,0,0,2,5
74,3,True,32.00,0,0,56.4958,0,0,1,3,6
75,3,True,25.00,0,0,7.6500,0,0,1,1,5
76,3,True,30.00,0,0,7.8958,0,0,1,1,5
77,3,True,30.00,0,0,8.0500,0,0,1,2,5
78,2,True,0.83,0,2,29.0000,0,0,1,2,1
79,3,False,30.00,0,0,12.4750,0,0,1,2,5
80,3,True,22.00,0,0,9.0000,0,0,1,2,5
81,3,True,29.00,0,0,9.5000,0,0,1,2,5
82,3,False,30.00,0,0,7.7875,0,1,0,1,5
83,1,True,28.00,0,0,47.1000,0,0,1,3,5
84,2,False,17.00,0,0,10.5000,0,0,1,2,4
85,3,False,33.00,3,0,15.8500,0,0,1,2,6
86,3,True,16.00,1,3,34.3750,0,0,1,3,4
87,3,True,30.00,0,0,8.0500,0,0,1,2,5
88,1,False,23.00,3,2,263.0000,0,0,1,3,5
89,3,True,24.00,0,0,8.0500,0,0,1,2,5
90,3,True,29.00,0,0,8.0500,0,0,1,2,5
91,3,True,20.00,0,0,7.8542,0,0,1,1,5
92,1,True,46.00,1,0,61.1750,0,0,1,3,7
93,3,True,26.00,1,2,20.5750,0,0,1,2,5
94,3,True,59.00,0,0,7.2500,0,0,1,1,7
95,3,True,30.00,0,0,8.0500,0,0,1,2,5
96,1,True,71.00,0,0,34.6542,1,0,0,3,8
97,1,True,23.00,0,1,63.3583,1,0,0,3,5
98,2,False,34.00,0,1,23.0000,0,0,1,2,6
99,2,True,34.00,1,0,26.0000,0,0,1,2,6
100,3,False,28.00,0,0,7.8958,0,0,1,1,5
101,3,True,30.00,0,0,7.8958,0,0,1,1,5
102,1,True,21.00,0,1,77.2875,0,0,1,3,5
103,3,True,33.00,0,0,8.6542,0,0,1,2,6
104,3,True,37.00,2,0,7.9250,0,0,1,2,6
105,3,True,28.00,0,0,7.8958,0,0,1,1,5
106,3,False,21.00,0,0,7.6500,0,0,1,1,5
107,3,True,30.00,0,0,7.7750,0,0,1,1,5
108,3,True,38.00,0,0,7.8958,0,0,1,1,6
109,3,False,30.00,1,0,24.1500,0,1,0,2,5
110,1,True,47.00,0,0,52.0000,0,0,1,3,7
111,3,False,14.50,1,0,14.4542,1,0,0,2,4
112,3,True,22.00,0,0,8.0500,0,0,1,2,5
113,3,False,20.00,1,0,9.8250,0,0,1,2,5
114,3,False,17.00,0,0,14.4583,1,0,0,2,4
115,3,True,21.00,0,0,7.9250,0,0,1,2,5
116,3,True,70.50,0,0,7.7500,0,1,0,1,8
117,2,True,29.00,1,0,21.0000,0,0,1,2,5
118,1,True,24.00,0,1,247.5208,1,0,0,3,5
119,3,False,2.00,4,2,31.2750,0,0,1,3,2
120,2,True,21.00,2,0,73.5000,0,0,1,3,5
121,3,True,30.00,0,0,8.0500,0,0,1,2,5
122,2,True,32.50,1,0,30.0708,1,0,0,2,6
123,2,False,32.50,0,0,13.0000,0,0,1,2,6
124,1,True,54.00,0,1,77.2875,0,0,1,3,7
125,3,True,12.00,1,0,11.2417,1,0,0,2,3
126,3,True,30.00,0,0,7.7500,0,1,0,1,5
127,3,True,24.00,0,0,7.1417,0,0,1,1,5
128,3,False,30.00,1,1,22.3583,1,0,0,2,5
129,3,True,45.00,0,0,6.9750,0,0,1,1,6
130,3,True,33.00,0,0,7.8958,1,0,0,1,6
131,3,True,20.00,0,0,7.0500,0,0,1,1,5
132,3,False,47.00,1,0,14.5000,0,0,1,2,7
133,2,False,29.00,1,0,26.0000,0,0,1,2,5
134,2,True,25.00,0,0,13.0000,0,0,1,2,5
135,2,True,23.00,0,0,15.0458,1,0,0,2,5
136,1,False,19.00,0,2,26.2833,0,0,1,2,5
137,1,True,37.00,1,0,53.1000,0,0,1,3,6
138,3,True,16.00,0,0,9.2167,0,0,1,2,4
139,1,True,24.00,0,0,79.2000,1,0,0,3,5
140,3,False,30.00,0,2,15.2458,1,0,0,2,5
141,3,False,22.00,0,0,7.7500,0,0,1,1,5
142,3,False,24.00,1,0,15.8500,0,0,1,2,5
143,3,True,19.00,0,0,6.7500,0,1,0,1,5
144,2,True,18.00,0,0,11.5000,0,0,1,2,4
145,2,True,19.00,1,1,36.7500,0,0,1,3,5
146,3,True,27.00,0,0,7.7958,0,0,1,1,5
147,3,False,9.00,2,2,34.3750,0,0,1,3,3
148,2,True,36.50,0,2,26.0000,0,0,1,2,6
149,2,True,42.00,0,0,13.0000,0,0,1,2,6
150,2,True,51.00,0,0,12.5250,0,0,1,2,7
151,1,False,22.00,1,0,66.6000,0,0,1,3,5
152,3,True,55.50,0,0,8.0500,0,0,1,2,7
153,3,True,40.50,0,2,14.5000,0,0,1,2,6
154,3,True,30.00,0,0,7.3125,0,0,1,1,5
155,1,True,51.00,0,1,61.3792,1,0,0,3,7
156,3,False,16.00,0,0,7.7333,0,1,0,1,4
157,3,True,30.00,0,0,8.0500,0,0,1,2,5
158,3,True,30.00,0,0,8.6625,0,0,1,2,5
159,3,True,30.00,8,2,69.5500,0,0,1,3,5
160,3,True,44.00,0,1,16.1000,0,0,1,2,6
161,2,False,40.00,0,0,15.7500,0,0,1,2,6
162,3,True,26.00,0,0,7.7750,0,0,1,1,5
163,3,True,17.00,0,0,8.6625,0,0,1,2,4
164,3,True,1.00,4,1,39.6875,0,0,1,3,1
165,3,True,9.00,0,2,20.5250,0,0,1,2,3
166,1,False,30.00,0,1,55.0000,0,0,1,3,5
167,3,False,45.00,1,4,27.9000,0,0,1,2,6
168,1,True,30.00,0,0,25.9250,0,0,1,2,5
169,3,True,28.00,0,0,56.4958,0,0,1,3,5
170,1,True,61.00,0,0,33.5000,0,0,1,3,8
171,3,True,4.00,4,1,29.1250,0,1,0,2,2
172,3,False,1.00,1,1,11.1333,0,0,1,2,1
173,3,True,21.00,0,0,7.9250,0,0,1,2,5
174,1,True,56.00,0,0,30.6958,1,0,0,2,7
175,3,True,18.00,1,1,7.8542,0,0,1,1,4
176,3,True,30.00,3,1,25.4667,0,0,1,2,5
177,1,False,50.00,0,0,28.7125,1,0,0,2,7
178,2,True,30.00,0,0,13.0000,0,0,1,2,5
179,3,True,36.00,0,0,0.0000,0,0,1,1,6
180,3,False,30.00,8,2,69.5500,0,0,1,3,5
181,2,True,30.00,0,0,15.0500,1,0,0,2,5
182,3,True,9.00,4,2,31.3875,0,0,1,3,3
183,2,True,1.00,2,1,39.0000,0,0,1,3,1
184,3,False,4.00,0,2,22.0250,0,0,1,2,2
185,1,True,30.00,0,0,50.0000,0,0,1,3,5
186,3,False,30.00,1,0,15.5000,0,1,0,2,5
187,1,True,45.00,0,0,26.5500,0,0,1,2,6
188,3,True,40.00,1,1,15.5000,0,1,0,2,6
189,3,True,36.00,0,0,7.8958,0,0,1,1,6
190,2,False,32.00,0,0,13.0000,0,0,1,2,6
191,2,True,19.00,0,0,13.0000,0,0,1,2,5
192,3,False,19.00,1,0,7.8542,0,0,1,1,5
193,2,True,3.00,1,1,26.0000,0,0,1,2,2
194,1,False,44.00,0,0,27.7208,1,0,0,2,6
195,1,False,58.00,0,0,146.5208,1,0,0,3,7
196,3,True,30.00,0,0,7.7500,0,1,0,1,5
197,3,True,42.00,0,1,8.4042,0,0,1,2,6
198,3,False,30.00,0,0,7.7500,0,1,0,1,5
199,2,False,24.00,0,0,13.0000,0,0,1,2,5
200,3,True,28.00,0,0,9.5000,0,0,1,2,5
201,3,True,30.00,8,2,69.5500,0,0,1,3,5
202,3,True,34.00,0,0,6.4958,0,0,1,1,6
203,3,True,45.50,0,0,7.2250,1,0,0,1,7
204,3,True,18.00,0,0,8.0500,0,0,1,2,4
205,3,False,2.00,0,1,10.4625,0,0,1,2,2
206,3,True,32.00,1,0,15.8500,0,0,1,2,6
207,3,True,26.00,0,0,18.7875,1,0,0,2,5
208,3,False,16.00,0,0,7.7500,0,1,0,1,4
209,1,True,40.00,0,0,31.0000,1,0,0,2,6
210,3,True,24.00,0,0,7.0500,0,0,1,1,5
211,2,False,35.00,0,0,21.0000,0,0,1,2,6
212,3,True,22.00,0,0,7.2500,0,0,1,1,5
213,2,True,30.00,0,0,13.0000,0,0,1,2,5
214,3,True,30.00,1,0,7.7500,0,1,0,1,5
215,1,False,31.00,1,0,113.2750,1,0,0,3,6
216,3,False,27.00,0,0,7.9250,0,0,1,2,5
217,2,True,42.00,1,0,27.0000,0,0,1,2,6
218,1,False,32.00,0,0,76.2917,1,0,0,3,6
219,2,True,30.00,0,0,10.5000,0,0,1,2,5
220,3,True,16.00,0,0,8.0500,0,0,1,2,4
221,2,True,27.00,0,0,13.0000,0,0,1,2,5
222,3,True,51.00,0,0,8.0500,0,0,1,2,7
223,3,True,30.00,0,0,7.8958,0,0,1,1,5
224,1,True,38.00,1,0,90.0000,0,0,1,3,6
225,3,True,22.00,0,0,9.3500,0,0,1,2,5
226,2,True,19.00,0,0,10.5000,0,0,1,2,5
227,3,True,20.50,0,0,7.2500,0,0,1,1,5
228,2,True,18.00,0,0,13.0000,0,0,1,2,4
229,3,False,30.00,3,1,25.4667,0,0,1,2,5
230,1,False,35.00,1,0,83.4750,0,0,1,3,6
231,3,True,29.00,0,0,7.7750,0,0,1,1,5
232,2,True,59.00,0,0,13.5000,0,0,1,2,7
233,3,False,5.00,4,2,31.3875,0,0,1,3,2
234,2,True,24.00,0,0,10.5000,0,0,1,2,5
235,3,False,30.00,0,0,7.5500,0,0,1,1,5
236,2,True,44.00,1,0,26.0000,0,0,1,2,6
237,2,False,8.00,0,2,26.2500,0,0,1,2,3
238,2,True,19.00,0,0,10.5000,0,0,1,2,5
239,2,True,33.00,0,0,12.2750,0,0,1,2,6
240,3,False,30.00,1,0,14.4542,1,0,0,2,5
241,3,False,30.00,1,0,15.5000,0,1,0,2,5
242,2,True,29.00,0,0,10.5000,0,0,1,2,5
243,3,True,22.00,0,0,7.1250,0,0,1,1,5
244,3,True,30.00,0,0,7.2250,1,0,0,1,5
245,1,True,44.00,2,0,90.0000,0,1,0,3,6
246,3,False,25.00,0,0,7.7750,0,0,1,1,5
247,2,False,24.00,0,2,14.5000,0,0,1,2,5
248,1,True,37.00,1,1,52.5542,0,0,1,3,6
249,2,True,54.00,1,0,26.0000,0,0,1,2,7
250,3,True,30.00,0,0,7.2500,0,0,1,1,5
251,3,False,29.00,1,1,10.4625,0,0,1,2,5
252,1,True,62.00,0,0,26.5500,0,0,1,2,8
253,3,True,30.00,1,0,16.1000,0,0,1,2,5
254,3,False,41.00,0,2,20.2125,0,0,1,2,6
255,3,False,29.00,0,2,15.2458,1,0,0,2,5
256,1,False,30.00,0,0,79.2000,1,0,0,3,5
257,1,False,30.00,0,0,86.5000,0,0,1,3,5
258,1,False,35.00,0,0,512.3292,1,0,0,3,6
259,2,False,50.00,0,1,26.0000,0,0,1,2,7
260,3,True,30.00,0,0,7.7500,0,1,0,1,5
261,3,True,3.00,4,2,31.3875,0,0,1,3,2
262,1,True,52.00,1,1,79.6500,0,0,1,3,7
263,1,True,40.00,0,0,0.0000,0,0,1,1,6
264,3,False,30.00,0,0,7.7500,0,1,0,1,5
265,2,True,36.00,0,0,10.5000,0,0,1,2,6
266,3,True,16.00,4,1,39.6875,0,0,1,3,4
267,3,True,25.00,1,0,7.7750,0,0,1,1,5
268,1,False,58.00,0,1,153.4625,0,0,1,3,7
269,1,False,35.00,0,0,135.6333,0,0,1,3,6
270,1,True,30.00,0,0,31.0000,0,0,1,2,5
271,3,True,25.00,0,0,0.0000,0,0,1,1,5
272,2,False,41.00,0,1,19.5000,0,0,1,2,6
273,1,True,37.00,0,1,29.7000,1,0,0,2,6
274,3,False,30.00,0,0,7.7500,0,1,0,1,5
275,1,False,63.00,1,0,77.9583,0,0,1,3,8
276,3,False,45.00,0,0,7.7500,0,0,1,1,6
277,2,True,30.00,0,0,0.0000,0,0,1,1,5
278,3,True,7.00,4,1,29.1250,0,1,0,2,3
279,3,False,35.00,1,1,20.2500,0,0,1,2,6
280,3,True,65.00,0,0,7.7500,0,1,0,1,8
281,3,True,28.00,0,0,7.8542,0,0,1,1,5
282,3,True,16.00,0,0,9.5000,0,0,1,2,4
283,3,True,19.00,0,0,8.0500,0,0,1,2,5
284,1,True,30.00,0,0,26.0000,0,0,1,2,5
285,3,True,33.00,0,0,8.6625,1,0,0,2,6
286,3,True,30.00,0,0,9.5000,0,0,1,2,5
287,3,True,22.00,0,0,7.8958,0,0,1,1,5
288,2,True,42.00,0,0,13.0000,0,0,1,2,6
289,3,False,22.00,0,0,7.7500,0,1,0,1,5
290,1,False,26.00,0,0,78.8500,0,0,1,3,5
291,1,False,19.00,1,0,91.0792,1,0,0,3,5
292,2,True,36.00,0,0,12.8750,1,0,0,2,6
293,3,False,24.00,0,0,8.8500,0,0,1,2,5
294,3,True,24.00,0,0,7.8958,0,0,1,1,5
295,1,True,30.00,0,0,27.7208,1,0,0,2,5
296,3,True,23.50,0,0,7.2292,1,0,0,1,5
297,1,False,2.00,1,2,151.5500,0,0,1,3,2
298,1,True,30.00,0,0,30.5000,0,0,1,2,5
299,1,False,50.00,0,1,247.5208,1,0,0,3,7
300,3,False,30.00,0,0,7.7500,0,1,0,1,5
301,3,True,30.00,2,0,23.2500,0,1,0,2,5
302,3,True,19.00,0,0,0.0000,0,0,1,1,5
303,2,False,30.00,0,0,12.3500,0,1,0,2,5
304,3,True,30.00,0,0,8.0500,0,0,1,2,5
305,1,True,0.92,1,2,151.5500,0,0,1,3,1
306,1,False,30.00,0,0,110.8833,1,0,0,3,5
307,1,False,17.00,1,0,108.9000,1,0,0,3,4
308,2,True,30.00,1,0,24.0000,1,0,0,2,5
309,1,False,30.00,0,0,56.9292,1,0,0,3,5
310,1,False,24.00,0,0,83.1583,1,0,0,3,5
311,1,False,18.00,2,2,262.3750,1,0,0,3,4
312,2,False,26.00,1,1,26.0000,0,0,1,2,5
313,3,True,28.00,0,0,7.8958,0,0,1,1,5
314,2,True,43.00,1,1,26.2500,0,0,1,2,6
315,3,False,26.00,0,0,7.8542,0,0,1,1,5
316,2,False,24.00,1,0,26.0000,0,0,1,2,5
317,2,True,54.00,0,0,14.0000,0,0,1,2,7
318,1,False,31.00,0,2,164.8667,0,0,1,3,6
319,1,False,40.00,1,1,134.5000,1,0,0,3,6
320,3,True,22.00,0,0,7.2500,0,0,1,1,5
321,3,True,27.00,0,0,7.8958,0,0,1,1,5
322,2,False,30.00,0,0,12.3500,0,1,0,2,5
323,2,False,22.00,1,1,29.0000,0,0,1,2,5
324,3,True,30.00,8,2,69.5500,0,0,1,3,5
325,1,False,36.00,0,0,135.6333,1,0,0,3,6
326,3,True,61.00,0,0,6.2375,0,0,1,1,8
327,2,False,36.00,0,0,13.0000,0,0,1,2,6
328,3,False,31.00,1,1,20.5250,0,0,1,2,6
329,1,False,16.00,0,1,57.9792,1,0,0,3,4
330,3,False,30.00,2,0,23.2500,0,1,0,2,5
331,1,True,45.50,0,0,28.5000,0,0,1,2,7
332,1,True,38.00,0,1,153.4625,0,0,1,3,6
333,3,True,16.00,2,0,18.0000,0,0,1,2,4
334,1,False,30.00,1,0,133.6500,0,0,1,3,5
335,3,True,30.00,0,0,7.8958,0,0,1,1,5
336,1,True,29.00,1,0,66.6000,0,0,1,3,5
337,1,False,41.00,0,0,134.5000,1,0,0,3,6
338,3,True,45.00,0,0,8.0500,0,0,1,2,6
339,1,True,45.00,0,0,35.5000,0,0,1,3,6
340,2,True,2.00,1,1,26.0000,0,0,1,2,2
341,1,False,24.00,3,2,263.0000,0,0,1,3,5
342,2,True,28.00,0,0,13.0000,0,0,1,2,5
343,2,True,25.00,0,0,13.0000,0,0,1,2,5
344,2,True,36.00,0,0,13.0000,0,0,1,2,6
345,2,False,24.00,0,0,13.0000,0,0,1,2,5
346,2,False,40.00,0,0,13.0000,0,0,1,2,6
347,3,False,30.00,1,0,16.1000,0,0,1,2,5
348,3,True,3.00,1,1,15.9000,0,0,1,2,2
349,3,True,42.00,0,0,8.6625,0,0,1,2,6
350,3,True,23.00,0,0,9.2250,0,0,1,2,5
351,1,True,30.00,0,0,35.0000,0,0,1,3,5
352,3,True,15.00,1,1,7.2292,1,0,0,1,4
353,3,True,25.00,1,0,17.8000,0,0,1,2,5
354,3,True,30.00,0,0,7.2250,1,0,0,1,5
355,3,True,28.00,0,0,9.5000,0,0,1,2,5
356,1,False,22.00,0,1,55.0000,0,0,1,3,5
357,2,False,38.00,0,0,13.0000,0,0,1,2,6
358,3,False,30.00,0,0,7.8792,0,1,0,1,5
359,3,False,30.00,0,0,7.8792,0,1,0,1,5
360,3,True,40.00,1,4,27.9000,0,0,1,2,6
361,2,True,29.00,1,0,27.7208,1,0,0,2,5
362,3,False,45.00,0,1,14.4542,1,0,0,2,6
363,3,True,35.00,0,0,7.0500,0,0,1,1,6
364,3,True,30.00,1,0,15.5000,0,1,0,2,5
365,3,True,30.00,0,0,7.2500,0,0,1,1,5
366,1,False,60.00,1,0,75.2500,1,0,0,3,7
367,3,False,30.00,0,0,7.2292,1,0,0,1,5
368,3,False,30.00,0,0,7.7500,0,1,0,1,5
369,1,False,24.00,0,0,69.3000,1,0,0,3,5
370,1,True,25.00,1,0,55.4417,1,0,0,3,5
371,3,True,18.00,1,0,6.4958,0,0,1,1,4
372,3,True,19.00,0,0,8.0500,0,0,1,2,5
373,1,True,22.00,0,0,135.6333,1,0,0,3,5
374,3,False,3.00,3,1,21.0750,0,0,1,2,2
375,1,False,30.00,1,0,82.1708,1,0,0,3,5
376,3,False,22.00,0,0,7.2500,0,0,1,1,5
377,1,True,27.00,0,2,211.5000,1,0,0,3,5
378,3,True,20.00,0,0,4.0125,1,0,0,1,5
379,3,True,19.00,0,0,7.7750,0,0,1,1,5
380,1,False,42.00,0,0,227.5250,1,0,0,3,6
381,3,False,1.00,0,2,15.7417,1,0,0,2,1
382,3,True,32.00,0,0,7.9250,0,0,1,2,6
383,1,False,35.00,1,0,52.0000,0,0,1,3,6
384,3,True,30.00,0,0,7.8958,0,0,1,1,5
385,2,True,18.00,0,0,73.5000,0,0,1,3,4
386,3,True,1.00,5,2,46.9000,0,0,1,3,1
387,2,False,36.00,0,0,13.0000,0,0,1,2,6
388,3,True,30.00,0,0,7.7292,0,1,0,1,5
389,2,False,17.00,0,0,12.0000,1,0,0,2,4
390,1,True,36.00,1,2,120.0000,0,0,1,3,6
391,3,True,21.00,0,0,7.7958,0,0,1,1,5
392,3,True,28.00,2,0,7.9250,0,0,1,2,5
393,1,False,23.00,1,0,113.2750,1,0,0,3,5
394,3,False,24.00,0,2,16.7000,0,0,1,2,5
395,3,True,22.00,0,0,7.7958,0,0,1,1,5
396,3,False,31.00,0,0,7.8542,0,0,1,1,6
397,2,True,46.00,0,0,26.0000,0,0,1,2,7
398,2,True,23.00,0,0,10.5000,0,0,1,2,5
399,2,False,28.00,0,0,12.6500,0,0,1,2,5
400,3,True,39.00,0,0,7.9250,0,0,1,2,6
401,3,True,26.00,0,0,8.0500,0,0,1,2,5
402,3,False,21.00,1,0,9.8250,0,0,1,2,5
403,3,True,28.00,1,0,15.8500,0,0,1,2,5
404,3,False,20.00,0,0,8.6625,0,0,1,2,5
405,2,True,34.00,1,0,21.0000,0,0,1,2,6
406,3,True,51.00,0,0,7.7500,0,0,1,1,7
407,2,True,3.00,1,1,18.7500,0,0,1,2,2
408,3,True,21.00,0,0,7.7750,0,0,1,1,5
409,3,False,30.00,3,1,25.4667,0,0,1,2,5
410,3,True,30.00,0,0,7.8958,0,0,1,1,5
411,3,True,30.00,0,0,6.8583,0,1,0,1,5
412,1,False,33.00,1,0,90.0000,0,1,0,3,6
413,2,True,30.00,0,0,0.0000,0,0,1,1,5
414,3,True,44.00,0,0,7.9250,0,0,1,2,6
415,3,False,30.00,0,0,8.0500,0,0,1,2,5
416,2,False,34.00,1,1,32.5000,0,0,1,3,6
417,2,False,18.00,0,2,13.0000,0,0,1,2,4
418,2,True,30.00,0,0,13.0000,0,0,1,2,5
419,3,False,10.00,0,2,24.1500,0,0,1,2,3
420,3,True,30.00,0,0,7.8958,1,0,0,1,5
421,3,True,21.00,0,0,7.7333,0,1,0,1,5
422,3,True,29.00,0,0,7.8750,0,0,1,1,5
423,3,False,28.00,1,1,14.4000,0,0,1,2,5
424,3,True,18.00,1,1,20.2125,0,0,1,2,4
425,3,True,30.00,0,0,7.2500,0,0,1,1,5
426,2,False,28.00,1,0,26.0000,0,0,1,2,5
427,2,False,19.00,0,0,26.0000,0,0,1,2,5
428,3,True,30.00,0,0,7.7500,0,1,0,1,5
429,3,True,32.00,0,0,8.0500,0,0,1,2,6
430,1,True,28.00,0,0,26.5500,0,0,1,2,5
431,3,False,30.00,1,0,16.1000,0,0,1,2,5
432,2,False,42.00,1,0,26.0000,0,0,1,2,6
433,3,True,17.00,0,0,7.1250,0,0,1,1,4
434,1,True,50.00,1,0,55.9000,0,0,1,3,7
435,1,False,14.00,1,2,120.0000,0,0,1,3,4
436,3,False,21.00,2,2,34.3750,0,0,1,3,5
437,2,False,24.00,2,3,18.7500,0,0,1,2,5
438,1,True,64.00,1,4,263.0000,0,0,1,3,8
439,2,True,31.00,0,0,10.5000,0,0,1,2,6
440,2,False,45.00,1,1,26.2500,0,0,1,2,6
441,3,True,20.00,0,0,9.5000,0,0,1,2,5
442,3,True,25.00,1,0,7.7750,0,0,1,1,5
443,2,False,28.00,0,0,13.0000,0,0,1,2,5
444,3,True,30.00,0,0,8.1125,0,0,1,2,5
445,1,True,4.00,0,2,81.8583,0,0,1,3,2
446,2,False,13.00,0,1,19.5000,0,0,1,2,4
447,1,True,34.00,0,0,26.5500,0,0,1,2,6
448,3,False,5.00,2,1,19.2583,1,0,0,2,2
449,1,True,52.00,0,0,30.5000,0,0,1,2,7
450,2,True,36.00,1,2,27.7500,0,0,1,2,6
451,3,True,30.00,1,0,19.9667,0,0,1,2,5
452,1,True,30.00,0,0,27.7500,1,0,0,2,5
453,1,True,49.00,1,0,89.1042,1,0,0,3,7
454,3,True,30.00,0,0,8.0500,0,0,1,2,5
455,3,True,29.00,0,0,7.8958,1,0,0,1,5
456,1,True,65.00,0,0,26.5500,0,0,1,2,8
457,1,False,30.00,1,0,51.8625,0,0,1,3,5
458,2,False,50.00,0,0,10.5000,0,0,1,2,7
459,3,True,30.00,0,0,7.7500,0,1,0,1,5
460,1,True,48.00,0,0,26.5500,0,0,1,2,7
461,3,True,34.00,0,0,8.0500,0,0,1,2,6
462,1,True,47.00,0,0,38.5000,0,0,1,3,7
463,2,True,48.00,0,0,13.0000,0,0,1,2,7
464,3,True,30.00,0,0,8.0500,0,0,1,2,5
465,3,True,38.00,0,0,7.0500,0,0,1,1,6
466,2,True,30.00,0,0,0.0000,0,0,1,1,5
467,1,True,56.00,0,0,26.5500,0,0,1,2,7
468,3,True,30.00,0,0,7.7250,0,1,0,1,5
469,3,False,0.75,2,1,19.2583,1,0,0,2,1
470,3,True,30.00,0,0,7.2500,0,0,1,1,5
471,3,True,38.00,0,0,8.6625,0,0,1,2,6
472,2,False,33.00,1,2,27.7500,0,0,1,2,6
473,2,False,23.00,0,0,13.7917,1,0,0,2,5
474,3,False,22.00,0,0,9.8375,0,0,1,2,5
475,1,True,30.00,0,0,52.0000,0,0,1,3,5
476,2,True,34.00,1,0,21.0000,0,0,1,2,6
477,3,True,29.00,1,0,7.0458,0,0,1,1,5
478,3,True,22.00,0,0,7.5208,0,0,1,1,5
479,3,False,2.00,0,1,12.2875,0,0,1,2,2
480,3,True,9.00,5,2,46.9000,0,0,1,3,3
481,2,True,30.00,0,0,0.0000,0,0,1,1,5
482,3,True,50.00,0,0,8.0500,0,0,1,2,7
483,3,False,63.00,0,0,9.5875,0,0,1,2,8
484,1,True,25.00,1,0,91.0792,1,0,0,3,5
485,3,False,30.00,3,1,25.4667,0,0,1,2,5
486,1,False,35.00,1,0,90.0000,0,0,1,3,6
487,1,True,58.00,0,0,29.7000,1,0,0,2,7
488,3,True,30.00,0,0,8.0500,0,0,1,2,5
489,3,True,9.00,1,1,15.9000,0,0,1,2,3
490,3,True,30.00,1,0,19.9667,0,0,1,2,5
491,3,True,21.00,0,0,7.2500,0,0,1,1,5
492,1,True,55.00,0,0,30.5000,0,0,1,2,7
493,1,True,71.00,0,0,49.5042,1,0,0,3,8
494,3,True,21.00,0,0,8.0500,0,0,1,2,5
495,3,True,30.00,0,0,14.4583,1,0,0,2,5
496,1,False,54.00,1,0,78.2667,1,0,0,3,7
497,3,True,30.00,0,0,15.1000,0,0,1,2,5
498,1,False,25.00,1,2,151.5500,0,0,1,3,5
499,3,True,24.00,0,0,7.7958,0,0,1,1,5
500,3,True,17.00,0,0,8.6625,0,0,1,2,4
501,3,False,21.00,0,0,7.7500,0,1,0,1,5
502,3,False,30.00,0,0,7.6292,0,1,0,1,5
503,3,False,37.00,0,0,9.5875,0,0,1,2,6
504,1,False,16.00,0,0,86.5000,0,0,1,3,4
505,1,True,18.00,1,0,108.9000,1,0,0,3,4
506,2,False,33.00,0,2,26.0000,0,0,1,2,6
507,1,True,30.00,0,0,26.5500,0,0,1,2,5
508,3,True,28.00,0,0,22.5250,0,0,1,2,5
509,3,True,26.00,0,0,56.4958,0,0,1,3,5
510,3,True,29.00,0,0,7.7500,0,1,0,1,5
511,3,True,30.00,0,0,8.0500,0,0,1,2,5
512,1,True,36.00,0,0,26.2875,0,0,1,2,6

In [36]:
pred = model.predict(test)

In [37]:
t = pd.read_csv('test.csv')
print(t['PassengerId'])

0       892
1       893
2       894
3       895
4       896
5       897
6       898
7       899
8       900
9       901
10      902
11      903
12      904
13      905
14      906
15      907
16      908
17      909
18      910
19      911
20      912
21      913
22      914
23      915
24      916
25      917
26      918
27      919
28      920
29      921
30      922
31      923
32      924
33      925
34      926
35      927
36      928
37      929
38      930
39      931
40      932
41      933
42      934
43      935
44      936
45      937
46      938
47      939
48      940
49      941
50      942
51      943
52      944
53      945
54      946
55      947
56      948
57      949
58      950
59      951
60      952
61      953
62      954
63      955
64      956
65      957
66      958
67      959
68      960
69      961
70      962
71      963
72      964
73      965
74      966
75      967
76      968
77      969
78      970
79      971
80      972
81      973
82      974
83      975
84      976
85      977
86      978
87      979
88      980
89      981
90      982
91      983
92      984
93      985
94      986
95      987
96      988
97      989
98      990
99      991
100     992
101     993
102     994
103     995
104     996
105     997
106     998
107     999
108    1000
109    1001
110    1002
111    1003
112    1004
113    1005
114    1006
115    1007
116    1008
117    1009
118    1010
119    1011
120    1012
121    1013
122    1014
123    1015
124    1016
125    1017
126    1018
127    1019
128    1020
129    1021
130    1022
131    1023
132    1024
133    1025
134    1026
135    1027
136    1028
137    1029
138    1030
139    1031
140    1032
141    1033
142    1034
143    1035
144    1036
145    1037
146    1038
147    1039
148    1040
149    1041
150    1042
151    1043
152    1044
153    1045
154    1046
155    1047
156    1048
157    1049
158    1050
159    1051
160    1052
161    1053
162    1054
163    1055
164    1056
165    1057
166    1058
167    1059
168    1060
169    1061
170    1062
171    1063
172    1064
173    1065
174    1066
175    1067
176    1068
177    1069
178    1070
179    1071
180    1072
181    1073
182    1074
183    1075
184    1076
185    1077
186    1078
187    1079
188    1080
189    1081
190    1082
191    1083
192    1084
193    1085
194    1086
195    1087
196    1088
197    1089
198    1090
199    1091
200    1092
201    1093
202    1094
203    1095
204    1096
205    1097
206    1098
207    1099
208    1100
209    1101
210    1102
211    1103
212    1104
213    1105
214    1106
215    1107
216    1108
217    1109
218    1110
219    1111
220    1112
221    1113
222    1114
223    1115
224    1116
225    1117
226    1118
227    1119
228    1120
229    1121
230    1122
231    1123
232    1124
233    1125
234    1126
235    1127
236    1128
237    1129
238    1130
239    1131
240    1132
241    1133
242    1134
243    1135
244    1136
245    1137
246    1138
247    1139
248    1140
249    1141
250    1142
251    1143
252    1144
253    1145
254    1146
255    1147
256    1148
257    1149
258    1150
259    1151
260    1152
261    1153
262    1154
263    1155
264    1156
265    1157
266    1158
267    1159
268    1160
269    1161
270    1162
271    1163
272    1164
273    1165
274    1166
275    1167
276    1168
277    1169
278    1170
279    1171
280    1172
281    1173
282    1174
283    1175
284    1176
285    1177
286    1178
287    1179
288    1180
289    1181
290    1182
291    1183
292    1184
293    1185
294    1186
295    1187
296    1188
297    1189
298    1190
299    1191
300    1192
301    1193
302    1194
303    1195
304    1196
305    1197
306    1198
307    1199
308    1200
309    1201
310    1202
311    1203
312    1204
313    1205
314    1206
315    1207
316    1208
317    1209
318    1210
319    1211
320    1212
321    1213
322    1214
323    1215
324    1216
325    1217
326    1218
327    1219
328    1220
329    1221
330    1222
331    1223
332    1224
333    1225
334    1226
335    1227
336    1228
337    1229
338    1230
339    1231
340    1232
341    1233
342    1234
343    1235
344    1236
345    1237
346    1238
347    1239
348    1240
349    1241
350    1242
351    1243
352    1244
353    1245
354    1246
355    1247
356    1248
357    1249
358    1250
359    1251
360    1252
361    1253
362    1254
363    1255
364    1256
365    1257
366    1258
367    1259
368    1260
369    1261
370    1262
371    1263
372    1264
373    1265
374    1266
375    1267
376    1268
377    1269
378    1270
379    1271
380    1272
381    1273
382    1274
383    1275
384    1276
385    1277
386    1278
387    1279
388    1280
389    1281
390    1282
391    1283
392    1284
393    1285
394    1286
395    1287
396    1288
397    1289
398    1290
399    1291
400    1292
401    1293
402    1294
403    1295
404    1296
405    1297
406    1298
407    1299
408    1300
409    1301
410    1302
411    1303
412    1304
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, dtype: int64

In [38]:
print(pred.shape)

(418,)

In [39]:
subm = pd.DataFrame({'PassengerId':t['PassengerId'], 
                     'Survived':pred})
subm.to_csv('submission.csv', index=False)

In [40]:
xgb = XGBClassifier(n_estimators=500, learning_rate=0.05)
xgb.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.05, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=6, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=500, n_jobs=0,
              num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [54]:
result = cross_validate(xgb, df[features], df[target], cv=5)

In [55]:
result

{'fit_time': array([0.49237299, 0.36454368, 0.4651432 , 0.37235999, 0.39699435]),
 'score_time': array([0.00531411, 0.00519753, 0.00519228, 0.00509548, 0.00533652]),
 'test_score': array([0.79329609, 0.82022472, 0.84831461, 0.76966292, 0.86516854])}

In [59]:
model = result['test_score']
model

array([0.79329609, 0.82022472, 0.84831461, 0.76966292, 0.86516854])

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Survived    891 non-null    int64
 1   Pclass      891 non-null    int64
 2   Sex         891 non-null    bool
 3   Age         891 non-null    float64
 4   SibSp       891 non-null    int64
 5   Parch       891 non-null    int64
 6   Fare        891 non-null    float64
 7   Embarked_C  891 non-null    uint8
 8   Embarked_Q  891 non-null    uint8
 9   Embarked_S  891 non-null    uint8
 10  Fare_bin    891 non-null    int64
 11  Age_bin     891 non-null    int64
dtypes: bool(1), float64(2), int64(6), uint8(3)
memory usage: 59.3 KB

In [45]:
df.corr()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Fare_bin,Age_bin
Survived,1.000000,-0.338481,-0.543351,-0.070657,-0.035322,0.081629,0.257307,0.168240,0.003650,-0.155660,0.278828,-0.091510
Pclass,-0.338481,1.000000,0.131900,-0.329727,0.083081,0.018443,-0.549500,-0.243292,0.221009,0.081720,-0.613295,-0.304233
Sex,-0.543351,0.131900,1.000000,0.084660,-0.114631,-0.245489,-0.182333,-0.082853,-0.074115,0.125722,-0.227227,0.089058
Age,-0.070657,-0.329727,0.084660,1.000000,-0.232440,-0.180330,0.090632,0.032330,-0.010738,-0.029322,0.076585,0.934669
SibSp,-0.035322,0.083081,-0.114631,-0.232440,1.000000,0.414838,0.159651,-0.059528,-0.026354,0.070941,0.349465,-0.283585
Parch,0.081629,0.018443,-0.245489,-0.180330,0.414838,1.000000,0.216225,-0.011069,-0.081228,0.063036,0.339821,-0.246679
Fare,0.257307,-0.549500,-0.182333,0.090632,0.159651,0.216225,1.000000,0.269335,-0.117216,-0.166603,0.580370,0.083779
Embarked_C,0.168240,-0.243292,-0.082853,0.032330,-0.059528,-0.011069,0.269335,1.000000,-0.148258,-0.778359,0.163169,0.004829
Embarked_Q,0.003650,0.221009,-0.074115,-0.010738,-0.026354,-0.081228,-0.117216,-0.148258,1.000000,-0.496624,-0.276459,-0.036151
Embarked_S,-0.155660,0.081720,0.125722,-0.029322,0.070941,0.063036,-0.166603,-0.778359,-0.496624,1.000000,0.023852,0.011097
Fare_bin,0.278828,-0.613295,-0.227227,0.076585,0.349465,0.339821,0.580370,0.163169,-0.276459,0.023852,1.000000,0.038831
Age_bin,-0.091510,-0.304233,0.089058,0.934669,-0.283585,-0.246679,0.083779,0.004829,-0.036151,0.011097,0.038831,1.000000